# Generated by Django 6.1.1 on 2026-10-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='source',
            field=models.CharField(choices=[('opening', 'Opening stock'), ('manual', 'Manual entry'), ('sale', 'Sales order'), ('sale_cancel', 'Cancelled order'), ('purchase', 'Goods receipt'), ('purchase_return', 'Purchase return'), ('return_cancel', 'Cancelled purchase return')], default='manual', max_length=15),
        ),
    ]
