# Generated by Django 6.1.1 on 2026-10-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_stockmovement_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='source',
            field=models.CharField(choices=[('opening', 'Opening stock'), ('manual', 'Manual entry'), ('sale', 'Sales order'), ('sale_cancel', 'Cancelled order'), ('invoice', 'Sales invoice'), ('invoice_cancel', 'Cancelled invoice'), ('sale_return', 'Sales return'), ('sale_return_cancel', 'Cancelled sales return'), ('purchase', 'Goods receipt'), ('purchase_return', 'Purchase return'), ('return_cancel', 'Cancelled purchase return')], default='manual', max_length=20),
        ),
    ]
