# Generated by Django 6.1.1 on 2026-10-08 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesettings',
            name='work_end',
            field=models.TimeField(default=datetime.time(17, 30)),
        ),
        migrations.AddField(
            model_name='attendancesettings',
            name='work_start',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
