# Generated by Django 6.1.1 on 2026-10-09 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_working_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'default_permissions': (), 'ordering': ['-attendance_date', '-id'], 'permissions': [('check_in', 'Check in'), ('check_out', 'Check out / logout'), ('view_all', "View everyone's attendance (dashboard)"), ('leave_apply', 'Apply for leave / permission'), ('leave_view', "View every employee's leave / permission requests"), ('leave_approve', 'Approve leave / permission'), ('leave_reject', 'Reject leave / permission'), ('employee_view', 'View employees'), ('employee_manage', 'Add / edit / delete employees'), ('calendar_view', "View every employee's calendar"), ('report_view', 'View attendance reports'), ('report_export', 'Export attendance reports (PDF / Excel / CSV)'), ('settings_view', 'View attendance settings'), ('settings_manage', 'Change attendance settings'), ('holiday_manage', 'Add / edit / delete office holidays')]},
        ),
        migrations.AddField(
            model_name='attendancesettings',
            name='weekly_holiday',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=6),
        ),
        migrations.CreateModel(
            name='OfficeHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('date', models.DateField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
                'default_permissions': (),
            },
        ),
    ]
