# Generated by Django 6.1.1 on 2026-09-28 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('detail', models.CharField(blank=True, help_text='Licence / certificate number or issuing body', max_length=255)),
                ('valid_until', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['valid_until', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QualityAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_type', models.CharField(choices=[('internal', 'Internal Audit'), ('fssai', 'FSSAI Inspection'), ('iso', 'ISO Audit'), ('customer', 'Customer Audit'), ('supplier', 'Supplier Audit')], max_length=10)),
                ('date', models.DateField(db_index=True)),
                ('auditor', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=10)),
                ('findings', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='QualityTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField(db_index=True)),
                ('parameters', models.TextField(help_text='What was checked and the readings')),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('hold', 'Hold')], db_index=True, max_length=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_tests', to='production.productionbatch')),
                ('tested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-test_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QualityStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=120)),
                ('limit', models.CharField(help_text='e.g. ≤ 10% moisture', max_length=120)),
                ('product', models.ForeignKey(blank=True, help_text='Leave empty if it applies to all products', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_standards', to='inventory.product')),
            ],
            options={
                'ordering': ['parameter'],
                'constraints': [models.UniqueConstraint(fields=('parameter', 'product'), name='unique_standard_per_product')],
            },
        ),
    ]
