# Generated by Django 6.1.1 on 2026-10-01 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_stockmovement_source'),
        ('purchase', '0001_initial'),
        ('quality', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualitytest',
            name='batch',
        ),
        migrations.AddField(
            model_name='qualitytest',
            name='batch_number',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='lot / batch number'),
        ),
        migrations.AddField(
            model_name='qualitytest',
            name='goods_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_tests', to='purchase.goodsreceipt'),
        ),
        migrations.AddField(
            model_name='qualitytest',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_tests', to='purchase.rawmaterial'),
        ),
        migrations.AddField(
            model_name='qualitytest',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_tests', to='inventory.product'),
        ),
        migrations.AddConstraint(
            model_name='qualitytest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('material__isnull', True), ('product__isnull', False)), models.Q(('material__isnull', False), ('product__isnull', True)), _connector='OR'), name='quality_test_one_item'),
        ),
    ]
