# Generated by Django 6.1.1 on 2026-10-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0002_remove_qualitytest_batch_qualitytest_batch_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitytest',
            name='readings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
