# Generated by Django 6.1.1 on 2026-10-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_sales_gst_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='default GST % on sales')),
                ('default_purchase_gst_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='default GST % on purchases')),
                ('quotation_validity_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quotation_payment_terms', models.CharField(blank=True, max_length=255)),
                ('quotation_delivery_terms', models.CharField(blank=True, max_length=255)),
                ('quotation_terms', models.TextField(blank=True, verbose_name='quotation terms & conditions')),
                ('invoice_due_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('invoice_payment_terms', models.CharField(blank=True, max_length=255)),
                ('invoice_terms', models.TextField(blank=True, verbose_name='invoice terms & conditions')),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('bank_account_name', models.CharField(blank=True, max_length=150)),
                ('bank_account_number', models.CharField(blank=True, max_length=30)),
                ('bank_ifsc', models.CharField(blank=True, max_length=11, verbose_name='IFSC')),
                ('upi_id', models.CharField(blank=True, max_length=80, verbose_name='UPI ID')),
                ('authorised_signatory', models.CharField(blank=True, max_length=120)),
                ('default_supplier_credit_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'billing settings',
                'verbose_name_plural': 'billing settings',
            },
        ),
    ]
