# Generated by Django 6.1.1 on 2026-10-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='kind',
            field=models.CharField(choices=[('forecast', 'Forecast'), ('stock', 'Stock-out risk'), ('anomaly', 'Anomaly'), ('segment', 'Customer segment'), ('quality', 'Quality'), ('purchase', 'Purchase recommendation')], db_index=True, max_length=10),
        ),
    ]
