"""
Writes supabase/schema.sql: the full Postgres schema that `manage.py migrate` creates, for reading or for
pasting into the Supabase SQL editor. It also records the migrations as applied, so a later
`manage.py migrate` finds nothing left to do.

It runs every migration against a throwaway database on the server in SUPABASE_DB_URL and records the
statements, so the SQL is exactly what Django runs. The throwaway database is dropped afterwards; the
real database is never touched.

    python scripts/export_supabase_schema.py
"""
import os
import re
import sys
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE_DIR))
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")

OUTPUT = BASE_DIR / "supabase" / "schema.sql"
SCRATCH_DB = "hipa_schema_export"
# Introspection, bookkeeping and row writes Django runs while migrating; they aren't part of the schema.
# (Content types and permissions are rows that `manage.py migrate` creates itself.)
SKIP = re.compile(
    r"^\s*(SELECT|SHOW|SET|SAVEPOINT|RELEASE|ROLLBACK|BEGIN|COMMIT|INSERT|UPDATE|DELETE)\b|django_migrations", re.I
)


def main():
    import django

    django.setup()
    from django.conf import settings
    from django.core.management import call_command
    from django.db import connection, connections

    with connection.cursor() as cursor:
        cursor.execute(f'DROP DATABASE IF EXISTS "{SCRATCH_DB}" WITH (FORCE)')
        cursor.execute(f'CREATE DATABASE "{SCRATCH_DB}"')
    connection.close()
    real_name = settings.DATABASES["default"]["NAME"]
    settings.DATABASES["default"]["NAME"] = connections["default"].settings_dict["NAME"] = SCRATCH_DB

    statements = []

    def record(execute, sql, params, many, context):
        if not SKIP.search(sql):
            text = connection.ops.compose_sql(sql, params) if params and not many else sql
            statements.append(text.rstrip().rstrip(";") + ";")
        return execute(sql, params, many, context)

    try:
        with connection.execute_wrapper(record):
            call_command("migrate", interactive=False, verbosity=0)
        with connection.cursor() as cursor:
            cursor.execute('SELECT "app", "name" FROM "django_migrations" ORDER BY "id"')
            applied = cursor.fetchall()
    finally:
        connection.close()
        settings.DATABASES["default"]["NAME"] = connections["default"].settings_dict["NAME"] = real_name
        with connection.cursor() as cursor:
            cursor.execute(f'DROP DATABASE IF EXISTS "{SCRATCH_DB}" WITH (FORCE)')
        connection.close()

    lines = [
        "-- HIPA MASALA database schema for Supabase (Postgres).",
        "-- Generated by backend/scripts/export_supabase_schema.py from the Django migrations. Do not edit by hand.",
        "-- Either run `python manage.py migrate` (recommended), or run this file once in an empty project's SQL editor",
        "-- and then `python manage.py migrate` once, which adds Django's content types and permissions.",
        "",
        "BEGIN;",
        "",
        *statements,
        "",
        "-- Record the migrations as applied, so `manage.py migrate` skips them.",
        'CREATE TABLE IF NOT EXISTS "django_migrations" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, '
        '"app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" timestamp with time zone NOT NULL);',
        'INSERT INTO "django_migrations" ("app", "name", "applied") VALUES',
        ",\n".join(f"    ('{app}', '{name}', now())" for app, name in applied) + ";",
        'ALTER TABLE "django_migrations" ENABLE ROW LEVEL SECURITY;',
        "",
        "COMMIT;",
        "",
    ]
    OUTPUT.parent.mkdir(exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUTPUT}: {len(statements)} statements from {len(applied)} migrations")


if __name__ == "__main__":
    main()
