# Generated by Django 6.1.1 on 2026-09-28 10:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('capacity_kg_per_day', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('quantity_kg', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('start_date', models.DateField(db_index=True)),
                ('due_date', models.DateField()),
                ('stage', models.CharField(choices=[('scheduled', 'Scheduled'), ('cleaning', 'Cleaning'), ('grinding', 'Grinding'), ('packaging', 'Packaging'), ('completed', 'Completed'), ('hold', 'Hold')], db_index=True, default='scheduled', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('stock_recorded', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='inventory.product')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='production.productionline')),
            ],
            options={
                'verbose_name_plural': 'production batches',
                'ordering': ['-start_date', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('due_date__gte', models.F('start_date'))), name='batch_due_after_start'), models.CheckConstraint(condition=models.Q(('quantity_kg__gt', 0)), name='batch_quantity_positive')],
            },
        ),
    ]
