# Generated by Django 6.1.1 on 2026-10-01 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productionbatch',
            name='batch_due_after_start',
        ),
        migrations.RemoveConstraint(
            model_name='productionbatch',
            name='batch_quantity_positive',
        ),
        migrations.RemoveField(
            model_name='productionbatch',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='productionbatch',
            name='line',
        ),
        migrations.RemoveField(
            model_name='productionbatch',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductionLine',
        ),
    ]
