# Generated by Django 6.1.1 on 2026-10-01 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_remove_productionbatch_batch_due_after_start_and_more'),
        ('quality', '0002_remove_qualitytest_batch_qualitytest_batch_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductionBatch',
        ),
    ]
