import { Download, FileText } from 'lucide-react'
import { useState } from 'react'
import { reportsApi } from '../../../api/reportsApi'
import Badge from '../../../components/common/Badge'
import Button from '../../../components/common/Button'
import Card from '../../../components/common/Card'
import ErrorMessage from '../../../components/common/ErrorMessage'
import Table from '../../../components/common/Table'
import { useApi } from '../../../hooks/useApi'
import { useToast } from '../../../hooks/useToast'
import { formatDate, formatTime } from '../../../utils/formatters'
import { EXPORT_FORMATS, REPORT_TYPES } from '../reportTypes'

const PAGE_SIZE = 8
const typeLabel = (key) => REPORT_TYPES.find((t) => t.key === key)?.label ?? key
const formatLabel = (v) => EXPORT_FORMATS.find((f) => f.value === v)?.label ?? v?.toUpperCase()

/** Previously generated reports (GET /reports/) with downloads when ready. */
export default function RecentReports({ refreshKey, highlightType }) {
  const toast = useToast()
  const [page, setPage] = useState(1)
  const [downloading, setDownloading] = useState(null)
  const reports = useApi(() => reportsApi.list({ page, page_size: PAGE_SIZE }), [page, refreshKey])
  const rows = Array.isArray(reports.data?.results) ? reports.data.results : []
  const total = Number(reports.data?.count) || 0

  const download = async (r) => {
    setDownloading(r.id)
    try {
      await reportsApi.download(r)
    } catch (err) {
      toast.error(err.message)
    } finally {
      setDownloading(null)
    }
  }

  return (
    <Card title="Recent Reports" subtitle="Reports generated by your team" className="no-print" bodyClassName="card__body--flush">
      {reports.error && !reports.loading ? (
        <div className="card__pad">
          <ErrorMessage message={reports.error.message} onRetry={reports.reload} />
        </div>
      ) : (
        <Table
          compact
          loading={reports.loading}
          caption="Recent reports"
          data={rows}
          rowClassName={(r) => (r.type === highlightType ? 'row--highlight' : undefined)}
          emptyIcon={FileText}
          emptyTitle="No reports generated yet"
          emptyMessage="Use Generate Report to create one; it will be listed here."
          pagination={{ page, pageSize: PAGE_SIZE, total, onPageChange: setPage }}
          columns={[
            { key: 'name', header: 'Report', render: (r) => <strong>{r.name || typeLabel(r.type)}</strong> },
            { key: 'type', header: 'Type', render: (r) => typeLabel(r.type) },
            { key: 'range_label', header: 'Period', render: (r) => r.range_label || '—' },
            { key: 'format', header: 'Format', render: (r) => (r.format ? formatLabel(r.format) : '—') },
            {
              key: 'created_at',
              header: 'Generated',
              render: (r) => <span className="nowrap">{r.created_at ? `${formatDate(r.created_at)}, ${formatTime(r.created_at)}` : '—'}</span>,
            },
            { key: 'created_by', header: 'By', render: (r) => r.created_by || '—' },
            { key: 'status', header: 'Status', render: (r) => (r.status ? <Badge>{r.status}</Badge> : '—') },
            {
              key: 'download',
              sticky: true,
              header: <span className="sr-only">Download</span>,
              align: 'right',
              render: (r) =>
                r.download_available === true && (
                  <Button size="sm" variant="soft" icon={Download} loading={downloading === r.id} onClick={() => download(r)} aria-label={`Download ${r.name || typeLabel(r.type)}`}>
                    Download
                  </Button>
                ),
            },
          ]}
        />
      )}
    </Card>
  )
}
