# Generated by Django 6.1.1 on 2026-10-07 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('purchase', '0002_supplier_payment_cancelled'),
        ('sales', '0002_alter_salesorderitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sales_payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_transaction', to='sales.salespayment'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='supplier_payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_transaction', to='purchase.supplierpayment'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], db_index=True, default='completed', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('sales_payment__isnull', True), ('supplier_payment__isnull', True), _connector='OR'), name='transaction_one_source'),
        ),
    ]
