import { Download, ExternalLink, Printer } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import Button from './Button'
import ErrorMessage from './ErrorMessage'
import Loader from './Loader'
import Modal from './Modal'

/**
 * Shows a PDF generated by the backend (quotation, invoice) with Print, Download and Open in new tab.
 * load(): Promise<Blob>; onDownload(): saves the file with the server's file name.
 * autoPrint: opens the browser's print dialog as soon as the PDF has loaded.
 */
export default function PdfPreviewModal({ open, ...props }) {
  if (!open) return null
  // Mounted fresh on every open, so each preview starts empty and loads its own file
  return <PdfPreview {...props} />
}

function PdfPreview({ title, load, onDownload, autoPrint = false, onClose }) {
  const [state, setState] = useState({ url: null, error: null })
  const [downloading, setDownloading] = useState(false)
  const frame = useRef(null)
  const printed = useRef(false)

  useEffect(() => {
    let url = null
    let active = true
    load().then(
      (blob) => {
        url = URL.createObjectURL(blob)
        if (active) setState({ url, error: null })
        else URL.revokeObjectURL(url)
      },
      (error) => active && setState({ url: null, error }),
    )
    return () => {
      active = false
      if (url) URL.revokeObjectURL(url)
    }
    // The document is fixed while the preview is open
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const print = () => {
    try {
      frame.current?.contentWindow?.focus()
      frame.current?.contentWindow?.print()
    } catch {
      window.open(state.url, '_blank', 'noopener')
    }
  }

  const download = async () => {
    setDownloading(true)
    try {
      await onDownload()
    } finally {
      setDownloading(false)
    }
  }

  return (
    <Modal
      open
      onClose={onClose}
      title={title}
      size="xl"
      footer={
        <>
          <Button variant="outline" icon={ExternalLink} disabled={!state.url} onClick={() => window.open(state.url, '_blank', 'noopener')}>
            Open in New Tab
          </Button>
          <Button variant="outline" icon={Download} loading={downloading} onClick={download}>
            Download PDF
          </Button>
          <Button icon={Printer} disabled={!state.url} onClick={print}>
            Print
          </Button>
        </>
      }
    >
      {state.error ? (
        <ErrorMessage message={state.error.message} />
      ) : !state.url ? (
        <Loader label="Generating PDF…" />
      ) : (
        <iframe
          ref={frame}
          className="pdf-frame"
          title={title}
          src={state.url}
          onLoad={() => {
            if (autoPrint && !printed.current) {
              printed.current = true
              setTimeout(print, 300)
            }
          }}
        />
      )}
    </Modal>
  )
}
