# Generated by Django 6.1.1 on 2026-10-01 09:26

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_alter_stockmovement_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='material ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='material name')),
                ('category', models.CharField(choices=[('whole_spice', 'Whole Spices'), ('seed', 'Seeds'), ('herb', 'Dried Herbs & Leaves'), ('ground', 'Ground / Powder'), ('packaging', 'Packing Material'), ('other', 'Other')], db_index=True, max_length=12)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('l', 'Litre (l)'), ('ml', 'Millilitre (ml)'), ('pcs', 'Pieces'), ('pkt', 'Packet'), ('bag', 'Bag'), ('box', 'Box'), ('roll', 'Roll')], default='kg', max_length=4)),
                ('current_stock', models.DecimalField(decimal_places=3, default=Decimal('0'), editable=False, max_digits=12)),
                ('minimum_stock', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('reorder_level', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, help_text='Standard price per unit', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='purchase ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit', models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('l', 'Litre (l)'), ('ml', 'Millilitre (ml)'), ('pcs', 'Pieces'), ('pkt', 'Packet'), ('bag', 'Bag'), ('box', 'Box'), ('roll', 'Roll')], max_length=4)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('discount_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('gst_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('gst_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('purchase_date', models.DateField(db_index=True)),
                ('expected_receipt_date', models.DateField(blank=True, null=True)),
                ('payment_due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partially_received', 'Partially Received'), ('received', 'Received'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=18)),
                ('received_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), editable=False, max_digits=12)),
                ('returned_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='inventory.product')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='purchase.rawmaterial')),
            ],
            options={
                'ordering': ['-purchase_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='supplier ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='supplier name')),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^[0-9+\\-() ]{6,20}$', 'Enter a valid phone number.')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(db_index=True, max_length=80)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('gstin', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$', 'Enter a valid 15-character GSTIN.')], verbose_name='GSTIN')),
                ('payment_terms', models.CharField(blank=True, help_text='e.g. Net 30 days', max_length=120)),
                ('credit_days', models.PositiveSmallIntegerField(blank=True, help_text='Days after purchase that payment is due', null=True, validators=[django.core.validators.MaxValueValidator(365)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Usual supplier', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='purchase.supplier'),
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='return ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit', models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('l', 'Litre (l)'), ('ml', 'Millilitre (ml)'), ('pcs', 'Pieces'), ('pkt', 'Packet'), ('bag', 'Bag'), ('box', 'Box'), ('roll', 'Roll')], max_length=4)),
                ('return_date', models.DateField(db_index=True)),
                ('reason', models.CharField(choices=[('damaged', 'Damaged'), ('quality', 'Failed quality check'), ('wrong_item', 'Wrong item'), ('excess', 'Excess quantity'), ('expired', 'Expired'), ('other', 'Other')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=10)),
                ('remarks', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='inventory.product')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='purchase.purchase')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='purchase.rawmaterial')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='purchase.supplier')),
            ],
            options={
                'ordering': ['-return_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='purchase.supplier'),
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='payment ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_date', models.DateField(db_index=True)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('cash', 'Cash'), ('card', 'Card'), ('other', 'Other')], max_length=13)),
                ('transaction_reference', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue')], db_index=True, default='pending', max_length=14)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='purchase.purchase')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='purchase.supplier')),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='GRN number')),
                ('received_date', models.DateField(db_index=True)),
                ('received_quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('damaged_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('accepted_quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quality_status', models.CharField(choices=[('pending', 'Pending Inspection'), ('passed', 'Passed'), ('failed', 'Failed'), ('on_hold', 'On Hold')], db_index=True, default='pending', max_length=8)),
                ('remarks', models.CharField(blank=True, max_length=500)),
                ('stock_recorded', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='purchase.purchase')),
            ],
            options={
                'ordering': ['-received_date', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('received_quantity__gt', 0)), name='grn_received_positive'), models.CheckConstraint(condition=models.Q(('damaged_quantity__lte', models.F('received_quantity'))), name='grn_damaged_within_received'), models.CheckConstraint(condition=models.Q(('accepted_quantity__lte', django.db.models.expressions.CombinedExpression(models.F('received_quantity'), '-', models.F('damaged_quantity')))), name='grn_accepted_within_good')],
            },
        ),
        migrations.CreateModel(
            name='MaterialMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out')], max_length=3)),
                ('source', models.CharField(choices=[('opening', 'Opening stock'), ('goods_receipt', 'Goods receipt'), ('purchase_return', 'Purchase return'), ('return_cancel', 'Cancelled return'), ('usage', 'Used'), ('adjustment', 'Adjustment')], default='adjustment', max_length=15)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('date', models.DateField(db_index=True)),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='purchase.rawmaterial')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='raw_material_movement_positive')],
            },
        ),
        migrations.AddConstraint(
            model_name='rawmaterial',
            constraint=models.CheckConstraint(condition=models.Q(('current_stock__gte', 0)), name='raw_material_stock_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='rawmaterial',
            constraint=models.CheckConstraint(condition=models.Q(('reorder_level__gte', models.F('minimum_stock'))), name='material_reorder_at_or_above_min'),
        ),
        migrations.AddConstraint(
            model_name='purchasereturn',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('material__isnull', False), ('product__isnull', True)), models.Q(('material__isnull', True), ('product__isnull', False)), _connector='OR'), name='purchase_return_one_item'),
        ),
        migrations.AddConstraint(
            model_name='purchasereturn',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='purchase_return_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('material__isnull', False), ('product__isnull', True)), models.Q(('material__isnull', True), ('product__isnull', False)), _connector='OR'), name='purchase_one_item'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='purchase_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(condition=models.Q(('expected_receipt_date__isnull', True), ('expected_receipt_date__gte', models.F('purchase_date')), _connector='OR'), name='purchase_receipt_after_date'),
        ),
        migrations.AddConstraint(
            model_name='supplierpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='supplier_payment_positive'),
        ),
    ]
