# Generated by Django 6.1.1 on 2026-10-01 09:43

from django.db import migrations, models


def production_to_purchase(apps, schema_editor):
    """The Production Team role is retired; its users move to the Purchase Team."""
    apps.get_model("accounts", "User").objects.filter(role="production").update(role="purchase")


def purchase_to_production(apps, schema_editor):
    pass  # not reversible: purchase users created later can't be told apart


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Super Admin'), ('management', 'Management'), ('sales', 'Sales Team'), ('purchase', 'Purchase Team'), ('inventory', 'Inventory Team'), ('marketing', 'Marketing Team'), ('finance', 'Finance Team'), ('quality', 'Quality Team'), ('supply_chain', 'Supply Chain Team')], db_index=True, default='sales', max_length=20),
        ),
        migrations.RunPython(production_to_purchase, purchase_to_production),
    ]
