# Generated by Django 6.1.1 on 2026-10-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_superusers_are_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Super Admin'), ('management', 'Management'), ('sales', 'Sales Team'), ('purchase', 'Purchase Team'), ('inventory', 'Inventory Team'), ('marketing', 'Marketing Team'), ('finance', 'Accounts Team'), ('quality', 'Quality Team'), ('supply_chain', 'Supply Chain Team')], db_index=True, default='sales', max_length=20),
        ),
    ]
