# Generated by Django 6.1.1 on 2026-09-28 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('sales', 'Sales Report'), ('inventory', 'Inventory Report'), ('production', 'Production Report'), ('marketing', 'Marketing Report'), ('customers', 'Customer Report'), ('supply_chain', 'Supply Chain Report'), ('quality', 'Quality Report'), ('finance', 'Finance Report')], db_index=True, max_length=15)),
                ('range', models.CharField(max_length=20)),
                ('range_label', models.CharField(max_length=60)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel'), ('csv', 'CSV')], max_length=4)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='processing', max_length=10)),
                ('file', models.FileField(blank=True, upload_to='reports/%Y/%m/')),
                ('error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
