# Generated by Django 6.1.1 on 2026-10-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('sales', 'Sales Report'), ('inventory', 'Inventory Report'), ('purchase', 'Purchase Report'), ('marketing', 'Marketing Report'), ('customers', 'Customer Report'), ('supply_chain', 'Supply Chain Report'), ('quality', 'Quality Report'), ('finance', 'Finance Report')], db_index=True, max_length=15),
        ),
    ]
