# Generated by Django 6.1.1 on 2026-10-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('sales', 'Sales Report'), ('quotations', 'Quotation Report'), ('inventory', 'Inventory Report'), ('purchase', 'Purchase Report'), ('marketing', 'Marketing Report'), ('customers', 'Customer Report'), ('supply_chain', 'Supply Chain Report'), ('quality', 'Quality Report'), ('ai_business', 'AI Business Report')], db_index=True, max_length=15),
        ),
    ]
