# Generated by Django 6.1.1 on 2026-10-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='content',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
