# Generated by Django 6.1.1 on 2026-09-28 10:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('whatsapp', 'WhatsApp'), ('google', 'Google Ads'), ('website', 'Website'), ('offline', 'Offline / Print')], max_length=12)),
                ('published_on', models.DateField(db_index=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['-views'],
            },
        ),
        migrations.CreateModel(
            name='AudienceSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('whatsapp', 'WhatsApp'), ('google', 'Google Ads'), ('website', 'Website'), ('offline', 'Offline / Print')], max_length=12)),
                ('name', models.CharField(max_length=60)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('as_of', models.DateField()),
            ],
            options={
                'ordering': ['platform', 'name'],
                'constraints': [models.UniqueConstraint(fields=('platform', 'name', 'as_of'), name='unique_audience_segment')],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('whatsapp', 'WhatsApp'), ('google', 'Google Ads'), ('website', 'Website'), ('offline', 'Offline / Print')], max_length=12)),
                ('objective', models.CharField(choices=[('awareness', 'Brand Awareness'), ('engagement', 'Engagement'), ('leads', 'Lead Generation'), ('sales', 'Sales'), ('launch', 'Product Launch')], max_length=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('description', models.TextField(blank=True)),
                ('ended_on', models.DateField(blank=True, help_text='Set when the campaign is ended early', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MarketingMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('whatsapp', 'WhatsApp'), ('google', 'Google Ads'), ('website', 'Website'), ('offline', 'Offline / Print')], max_length=12)),
                ('reach', models.PositiveIntegerField(default=0)),
                ('engagement', models.PositiveIntegerField(default=0)),
                ('website_visitors', models.PositiveIntegerField(default=0)),
                ('leads', models.PositiveIntegerField(default=0)),
                ('sales_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='marketing.campaign')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('whatsapp', 'WhatsApp'), ('google', 'Google Ads'), ('website', 'Website'), ('offline', 'Offline / Print')], max_length=12)),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('caption', models.TextField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('published', 'Published'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='marketing.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_for'],
            },
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='campaign_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='marketingmetric',
            constraint=models.UniqueConstraint(fields=('date', 'platform', 'campaign'), name='unique_metric_per_day'),
        ),
    ]
