# Generated by Django 6.1.1 on 2026-10-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='marketingmetric',
            name='unique_metric_per_day',
        ),
        migrations.AddConstraint(
            model_name='marketingmetric',
            constraint=models.UniqueConstraint(fields=('date', 'platform', 'campaign'), name='unique_metric_per_day', nulls_distinct=False),
        ),
    ]
