/**
 * CSV export of rows already on screen (e.g. the Sales product table).
 * columns: [{ key, header, value?(row) }]
 * Full reports and Excel/PDF files are generated by the server (see api.download).
 */

function cellValue(row, col) {
  const v = col.value ? col.value(row) : row[col.key]
  return v === null || v === undefined ? '' : v
}

function triggerDownload(blob, filename) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  a.remove()
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}

export function toCSV(rows, columns) {
  const esc = (v) => {
    const s = String(v)
    return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s
  }
  const lines = [columns.map((c) => esc(c.header)).join(',')]
  for (const row of rows) lines.push(columns.map((c) => esc(cellValue(row, c))).join(','))
  return lines.join('\r\n')
}

export function downloadCSV(filename, rows, columns) {
  // BOM so Excel shows ₹ and Tamil text correctly
  triggerDownload(new Blob(['﻿' + toCSV(rows, columns)], { type: 'text/csv;charset=utf-8' }), filename)
}
