-- HIPA MASALA database schema for Supabase (Postgres).
-- Generated by backend/scripts/export_supabase_schema.py from the Django migrations. Do not edit by hand.
-- Either run `python manage.py migrate` (recommended), or run this file once in an empty project's SQL editor
-- and then `python manage.py migrate` once, which adds Django's content types and permissions.

BEGIN;

CREATE TABLE "django_content_type" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
ALTER TABLE "django_content_type" ADD CONSTRAINT "django_content_type_app_label_model_76bd3d3b_uniq" UNIQUE ("app_label", "model");
ALTER TABLE "django_content_type" ALTER COLUMN "name" DROP NOT NULL;
ALTER TABLE "django_content_type" DROP COLUMN "name";
CREATE TABLE "auth_permission" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(50) NOT NULL, "content_type_id" integer NOT NULL, "codename" varchar(100) NOT NULL);
CREATE TABLE "auth_group" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(80) NOT NULL UNIQUE);
CREATE TABLE "auth_group_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "group_id" integer NOT NULL, "permission_id" integer NOT NULL);
ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_codename_01ab375a_uniq" UNIQUE ("content_type_id", "codename");
ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE INDEX "auth_group_name_a6ea08ec_like" ON "auth_group" ("name" varchar_pattern_ops);
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" UNIQUE ("group_id", "permission_id");
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
ALTER TABLE "auth_permission" ALTER COLUMN "name" TYPE varchar(255);
ALTER TABLE "auth_group" ALTER COLUMN "name" TYPE varchar(150);
CREATE TABLE "accounts_user" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "is_superuser" boolean NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "is_staff" boolean NOT NULL, "is_active" boolean NOT NULL, "date_joined" timestamp with time zone NOT NULL, "email" varchar(254) NOT NULL UNIQUE, "name" varchar(150) NOT NULL, "role" varchar(20) NOT NULL, "updated_at" timestamp with time zone NOT NULL);
CREATE TABLE "accounts_user_groups" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "group_id" integer NOT NULL);
CREATE TABLE "accounts_user_user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "permission_id" integer NOT NULL);
CREATE TABLE "accounts_loginactivity" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "username_attempted" varchar(254) NOT NULL, "success" boolean NOT NULL, "ip" inet NULL, "user_agent" varchar(300) NOT NULL, "created_at" timestamp with time zone NOT NULL, "user_id" bigint NULL);
CREATE INDEX "accounts_user_username_6088629e_like" ON "accounts_user" ("username" varchar_pattern_ops);
CREATE INDEX "accounts_user_email_b2644a56_like" ON "accounts_user" ("email" varchar_pattern_ops);
CREATE INDEX "accounts_user_role_57e97df0" ON "accounts_user" ("role");
CREATE INDEX "accounts_user_role_57e97df0_like" ON "accounts_user" ("role" varchar_pattern_ops);
ALTER TABLE "accounts_user_groups" ADD CONSTRAINT "accounts_user_groups_user_id_group_id_59c0b32f_uniq" UNIQUE ("user_id", "group_id");
ALTER TABLE "accounts_user_groups" ADD CONSTRAINT "accounts_user_groups_user_id_52b62117_fk_accounts_user_id" FOREIGN KEY ("user_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "accounts_user_groups" ADD CONSTRAINT "accounts_user_groups_group_id_bd11a704_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "accounts_user_groups_user_id_52b62117" ON "accounts_user_groups" ("user_id");
CREATE INDEX "accounts_user_groups_group_id_bd11a704" ON "accounts_user_groups" ("group_id");
ALTER TABLE "accounts_user_user_permissions" ADD CONSTRAINT "accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq" UNIQUE ("user_id", "permission_id");
ALTER TABLE "accounts_user_user_permissions" ADD CONSTRAINT "accounts_user_user_p_user_id_e4f0a161_fk_accounts_" FOREIGN KEY ("user_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "accounts_user_user_permissions" ADD CONSTRAINT "accounts_user_user_p_permission_id_113bb443_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "accounts_user_user_permissions_user_id_e4f0a161" ON "accounts_user_user_permissions" ("user_id");
CREATE INDEX "accounts_user_user_permissions_permission_id_113bb443" ON "accounts_user_user_permissions" ("permission_id");
ALTER TABLE "accounts_loginactivity" ADD CONSTRAINT "accounts_loginactivity_user_id_e23ed239_fk_accounts_user_id" FOREIGN KEY ("user_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "accounts_loginactivity_created_at_3bd831f6" ON "accounts_loginactivity" ("created_at");
CREATE INDEX "accounts_loginactivity_user_id_e23ed239" ON "accounts_loginactivity" ("user_id");
CREATE TABLE "django_admin_log" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "action_time" timestamp with time zone NOT NULL, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL, "user_id" bigint NOT NULL);
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_content_type_id_c4bce8eb_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_user_id_c564eba6_fk_accounts_user_id" FOREIGN KEY ("user_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE TABLE "ai_assistant_analyticsrun" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "started_at" timestamp with time zone NOT NULL, "finished_at" timestamp with time zone NULL, "summary" jsonb NOT NULL);
CREATE TABLE "ai_assistant_insight" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "kind" varchar(10) NOT NULL, "module" varchar(20) NOT NULL, "title" varchar(200) NOT NULL, "text" text NOT NULL, "action" varchar(255) NOT NULL, "data" jsonb NOT NULL, "created_at" timestamp with time zone NOT NULL);
CREATE TABLE "ai_assistant_conversation" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(200) NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "user_id" bigint NOT NULL);
CREATE TABLE "ai_assistant_message" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "role" varchar(10) NOT NULL, "text" text NOT NULL, "attachment_name" varchar(255) NOT NULL, "created_at" timestamp with time zone NOT NULL, "conversation_id" bigint NOT NULL);
CREATE INDEX "ai_assistant_insight_kind_b147a4c1" ON "ai_assistant_insight" ("kind");
CREATE INDEX "ai_assistant_insight_kind_b147a4c1_like" ON "ai_assistant_insight" ("kind" varchar_pattern_ops);
CREATE INDEX "ai_assistant_insight_module_f0b44168" ON "ai_assistant_insight" ("module");
CREATE INDEX "ai_assistant_insight_module_f0b44168_like" ON "ai_assistant_insight" ("module" varchar_pattern_ops);
CREATE INDEX "ai_assistant_insight_created_at_381e88b8" ON "ai_assistant_insight" ("created_at");
ALTER TABLE "ai_assistant_conversation" ADD CONSTRAINT "ai_assistant_conversation_user_id_5ee16771_fk_accounts_user_id" FOREIGN KEY ("user_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "ai_assistant_conversation_updated_at_3fa4588b" ON "ai_assistant_conversation" ("updated_at");
CREATE INDEX "ai_assistant_conversation_user_id_5ee16771" ON "ai_assistant_conversation" ("user_id");
ALTER TABLE "ai_assistant_message" ADD CONSTRAINT "ai_assistant_message_conversation_id_62fa3b00_fk_ai_assist" FOREIGN KEY ("conversation_id") REFERENCES "ai_assistant_conversation" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "ai_assistant_message_conversation_id_62fa3b00" ON "ai_assistant_message" ("conversation_id");
CREATE TABLE "customers_customeroffer" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "segment" varchar(20) NOT NULL, "channel" varchar(20) NOT NULL, "message" text NOT NULL, "recipients" integer NOT NULL CHECK ("recipients" >= 0), "created_at" timestamp with time zone NOT NULL, "sent_by_id" bigint NULL);
CREATE TABLE "customers_customer" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(150) NOT NULL, "type" varchar(20) NOT NULL, "contact_person" varchar(120) NOT NULL, "phone" varchar(20) NOT NULL, "email" varchar(254) NOT NULL, "city" varchar(80) NOT NULL, "address" text NOT NULL, "status" varchar(10) NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "created_by_id" bigint NULL, CONSTRAINT "unique_customer_name_city" UNIQUE ("name", "city"));
ALTER TABLE "customers_customeroffer" ADD CONSTRAINT "customers_customeroffer_sent_by_id_6053174f_fk_accounts_user_id" FOREIGN KEY ("sent_by_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "customers_customeroffer_sent_by_id_6053174f" ON "customers_customeroffer" ("sent_by_id");
ALTER TABLE "customers_customer" ADD CONSTRAINT "customers_customer_created_by_id_e3e9e010_fk_accounts_user_id" FOREIGN KEY ("created_by_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "customers_customer_type_0bea458c" ON "customers_customer" ("type");
CREATE INDEX "customers_customer_type_0bea458c_like" ON "customers_customer" ("type" varchar_pattern_ops);
CREATE INDEX "customers_customer_city_56690332" ON "customers_customer" ("city");
CREATE INDEX "customers_customer_city_56690332_like" ON "customers_customer" ("city" varchar_pattern_ops);
CREATE INDEX "customers_customer_status_743673e0" ON "customers_customer" ("status");
CREATE INDEX "customers_customer_status_743673e0_like" ON "customers_customer" ("status" varchar_pattern_ops);
CREATE INDEX "customers_customer_created_at_b0f7c38c" ON "customers_customer" ("created_at");
CREATE INDEX "customers_customer_created_by_id_e3e9e010" ON "customers_customer" ("created_by_id");
ALTER TABLE "customers_customer" ADD COLUMN "gstin" varchar(15) DEFAULT '' NOT NULL;
ALTER TABLE "customers_customer" ALTER COLUMN "gstin" DROP DEFAULT;
ALTER TABLE "customers_customer" ADD COLUMN "shipping_address" text DEFAULT '' NOT NULL;
ALTER TABLE "customers_customer" ALTER COLUMN "shipping_address" DROP DEFAULT;
CREATE TABLE "finance_budget" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "month" date NOT NULL UNIQUE, "revenue_target" numeric(14, 2) NOT NULL, "expense_limit" numeric(14, 2) NOT NULL, "updated_at" timestamp with time zone NOT NULL, "updated_by_id" bigint NULL);
CREATE TABLE "finance_transaction" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "date" date NOT NULL, "description" varchar(255) NOT NULL, "type" varchar(7) NOT NULL, "category" varchar(20) NOT NULL, "amount" numeric(14, 2) NOT NULL, "status" varchar(10) NOT NULL, "party" varchar(150) NOT NULL, "due_date" date NULL, "reference" varchar(60) NOT NULL, "created_at" timestamp with time zone NOT NULL, "created_by_id" bigint NULL, CONSTRAINT "transaction_amount_positive" CHECK ("amount" > 0));
ALTER TABLE "finance_budget" ADD CONSTRAINT "finance_budget_updated_by_id_8f98ef07_fk_accounts_user_id" FOREIGN KEY ("updated_by_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "finance_budget_updated_by_id_8f98ef07" ON "finance_budget" ("updated_by_id");
ALTER TABLE "finance_transaction" ADD CONSTRAINT "finance_transaction_created_by_id_c2f2b2b4_fk_accounts_user_id" FOREIGN KEY ("created_by_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "finance_transaction_date_5f8dd1cd" ON "finance_transaction" ("date");
CREATE INDEX "finance_transaction_type_3ccc96bf" ON "finance_transaction" ("type");
CREATE INDEX "finance_transaction_type_3ccc96bf_like" ON "finance_transaction" ("type" varchar_pattern_ops);
CREATE INDEX "finance_transaction_category_a185a8ea" ON "finance_transaction" ("category");
CREATE INDEX "finance_transaction_category_a185a8ea_like" ON "finance_transaction" ("category" varchar_pattern_ops);
CREATE INDEX "finance_transaction_status_61cce599" ON "finance_transaction" ("status");
CREATE INDEX "finance_transaction_status_61cce599_like" ON "finance_transaction" ("status" varchar_pattern_ops);
CREATE INDEX "finance_transaction_created_by_id_c2f2b2b4" ON "finance_transaction" ("created_by_id");
CREATE TABLE "inventory_product" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(120) NOT NULL UNIQUE, "price_per_kg" numeric(10, 2) NOT NULL, "min_stock_kg" numeric(12, 3) NOT NULL, "reorder_level_kg" numeric(12, 3) NOT NULL, "stock_kg" numeric(12, 3) NOT NULL, "is_active" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, CONSTRAINT "product_stock_not_negative" CHECK ("stock_kg" >= 0), CONSTRAINT "reorder_at_or_above_min" CHECK ("reorder_level_kg" >= ("min_stock_kg")));
CREATE TABLE "inventory_stockmovement" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "type" varchar(3) NOT NULL, "quantity_kg" numeric(12, 3) NOT NULL, "source" varchar(15) NOT NULL, "reference" varchar(50) NOT NULL, "note" varchar(255) NOT NULL, "created_at" timestamp with time zone NOT NULL, "created_by_id" bigint NULL, "product_id" bigint NOT NULL, CONSTRAINT "movement_quantity_positive" CHECK ("quantity_kg" > 0));
CREATE INDEX "inventory_product_name_78603733_like" ON "inventory_product" ("name" varchar_pattern_ops);
ALTER TABLE "inventory_stockmovement" ADD CONSTRAINT "inventory_stockmovem_created_by_id_9a39cb99_fk_accounts_" FOREIGN KEY ("created_by_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "inventory_stockmovement" ADD CONSTRAINT "inventory_stockmovem_product_id_4eccfd0a_fk_inventory" FOREIGN KEY ("product_id") REFERENCES "inventory_product" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "inventory_stockmovement_created_at_05b478ed" ON "inventory_stockmovement" ("created_at");
CREATE INDEX "inventory_stockmovement_created_by_id_9a39cb99" ON "inventory_stockmovement" ("created_by_id");
CREATE INDEX "inventory_stockmovement_product_id_4eccfd0a" ON "inventory_stockmovement" ("product_id");
ALTER TABLE "inventory_stockmovement" ALTER COLUMN "source" TYPE varchar(20);
CREATE TABLE "marketing_contentitem" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(200) NOT NULL, "platform" varchar(12) NOT NULL, "published_on" date NOT NULL, "views" integer NOT NULL CHECK ("views" >= 0), "likes" integer NOT NULL CHECK ("likes" >= 0), "shares" integer NOT NULL CHECK ("shares" >= 0), "url" varchar(200) NOT NULL);
CREATE TABLE "marketing_audiencesegment" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "platform" varchar(12) NOT NULL, "name" varchar(60) NOT NULL, "value" numeric(12, 2) NOT NULL, "as_of" date NOT NULL, CONSTRAINT "unique_audience_segment" UNIQUE ("platform", "name", "as_of"));
CREATE TABLE "marketing_campaign" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(150) NOT NULL, "platform" varchar(12) NOT NULL, "objective" varchar(12) NOT NULL, "start_date" date NOT NULL, "end_date" date NOT NULL, "budget" numeric(12, 2) NOT NULL, "description" text NOT NULL, "ended_on" date NULL, "created_at" timestamp with time zone NOT NULL, "created_by_id" bigint NULL);
CREATE TABLE "marketing_marketingmetric" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "date" date NOT NULL, "platform" varchar(12) NOT NULL, "reach" integer NOT NULL CHECK ("reach" >= 0), "engagement" integer NOT NULL CHECK ("engagement" >= 0), "website_visitors" integer NOT NULL CHECK ("website_visitors" >= 0), "leads" integer NOT NULL CHECK ("leads" >= 0), "sales_amount" numeric(14, 2) NOT NULL, "campaign_id" bigint NULL);
CREATE TABLE "marketing_scheduledpost" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "platform" varchar(12) NOT NULL, "scheduled_for" timestamp with time zone NOT NULL, "caption" text NOT NULL, "status" varchar(10) NOT NULL, "created_at" timestamp with time zone NOT NULL, "campaign_id" bigint NULL, "created_by_id" bigint NULL);
ALTER TABLE "marketing_campaign" ADD CONSTRAINT "campaign_end_after_start" CHECK ("end_date" >= ("start_date"));
ALTER TABLE "marketing_marketingmetric" ADD CONSTRAINT "unique_metric_per_day" UNIQUE ("date", "platform", "campaign_id");
CREATE INDEX "marketing_contentitem_published_on_8c9af51e" ON "marketing_contentitem" ("published_on");
ALTER TABLE "marketing_campaign" ADD CONSTRAINT "marketing_campaign_created_by_id_c4d2ec89_fk_accounts_user_id" FOREIGN KEY ("created_by_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "marketing_campaign_created_by_id_c4d2ec89" ON "marketing_campaign" ("created_by_id");
ALTER TABLE "marketing_marketingmetric" ADD CONSTRAINT "marketing_marketingm_campaign_id_3b96de34_fk_marketing" FOREIGN KEY ("campaign_id") REFERENCES "marketing_campaign" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "marketing_marketingmetric_date_27c9738f" ON "marketing_marketingmetric" ("date");
CREATE INDEX "marketing_marketingmetric_campaign_id_3b96de34" ON "marketing_marketingmetric" ("campaign_id");
ALTER TABLE "marketing_scheduledpost" ADD CONSTRAINT "marketing_scheduledp_campaign_id_7c3a9435_fk_marketing" FOREIGN KEY ("campaign_id") REFERENCES "marketing_campaign" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "marketing_scheduledpost" ADD CONSTRAINT "marketing_scheduledp_created_by_id_ffd49d2f_fk_accounts_" FOREIGN KEY ("created_by_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "marketing_scheduledpost_scheduled_for_4adbc17b" ON "marketing_scheduledpost" ("scheduled_for");
CREATE INDEX "marketing_scheduledpost_status_e68af102" ON "marketing_scheduledpost" ("status");
CREATE INDEX "marketing_scheduledpost_status_e68af102_like" ON "marketing_scheduledpost" ("status" varchar_pattern_ops);
CREATE INDEX "marketing_scheduledpost_campaign_id_7c3a9435" ON "marketing_scheduledpost" ("campaign_id");
CREATE INDEX "marketing_scheduledpost_created_by_id_ffd49d2f" ON "marketing_scheduledpost" ("created_by_id");
CREATE TABLE "production_productionline" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(80) NOT NULL UNIQUE, "capacity_kg_per_day" numeric(10, 2) NOT NULL, "is_active" boolean NOT NULL);
CREATE TABLE "production_productionbatch" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "batch_number" varchar(20) NOT NULL UNIQUE, "quantity_kg" numeric(12, 3) NOT NULL, "start_date" date NOT NULL, "due_date" date NOT NULL, "stage" varchar(10) NOT NULL, "completed_at" timestamp with time zone NULL, "stock_recorded" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "created_by_id" bigint NULL, "product_id" bigint NOT NULL, "line_id" bigint NOT NULL, CONSTRAINT "batch_due_after_start" CHECK ("due_date" >= ("start_date")), CONSTRAINT "batch_quantity_positive" CHECK ("quantity_kg" > 0));
CREATE INDEX "production_productionline_name_8479b87f_like" ON "production_productionline" ("name" varchar_pattern_ops);
ALTER TABLE "production_productionbatch" ADD CONSTRAINT "production_productio_created_by_id_ea05d344_fk_accounts_" FOREIGN KEY ("created_by_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "production_productionbatch" ADD CONSTRAINT "production_productio_product_id_8321ebb9_fk_inventory" FOREIGN KEY ("product_id") REFERENCES "inventory_product" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "production_productionbatch" ADD CONSTRAINT "production_productio_line_id_ba1b240d_fk_productio" FOREIGN KEY ("line_id") REFERENCES "production_productionline" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "production_productionbatch_batch_number_f4b77971_like" ON "production_productionbatch" ("batch_number" varchar_pattern_ops);
CREATE INDEX "production_productionbatch_start_date_b2db870b" ON "production_productionbatch" ("start_date");
CREATE INDEX "production_productionbatch_stage_1557a429" ON "production_productionbatch" ("stage");
CREATE INDEX "production_productionbatch_stage_1557a429_like" ON "production_productionbatch" ("stage" varchar_pattern_ops);
CREATE INDEX "production_productionbatch_created_by_id_ea05d344" ON "production_productionbatch" ("created_by_id");
CREATE INDEX "production_productionbatch_product_id_8321ebb9" ON "production_productionbatch" ("product_id");
CREATE INDEX "production_productionbatch_line_id_ba1b240d" ON "production_productionbatch" ("line_id");
CREATE TABLE "quality_certification" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(120) NOT NULL, "detail" varchar(255) NOT NULL, "valid_until" date NULL);
CREATE TABLE "quality_qualityaudit" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "audit_type" varchar(10) NOT NULL, "date" date NOT NULL, "auditor" varchar(120) NOT NULL, "status" varchar(10) NOT NULL, "findings" text NOT NULL, "created_at" timestamp with time zone NOT NULL, "created_by_id" bigint NULL);
CREATE TABLE "quality_qualitytest" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "test_date" date NOT NULL, "parameters" text NOT NULL, "result" varchar(5) NOT NULL, "notes" text NOT NULL, "created_at" timestamp with time zone NOT NULL, "batch_id" bigint NOT NULL, "tested_by_id" bigint NULL);
CREATE TABLE "quality_qualitystandard" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "parameter" varchar(120) NOT NULL, "limit" varchar(120) NOT NULL, "product_id" bigint NULL, CONSTRAINT "unique_standard_per_product" UNIQUE ("parameter", "product_id"));
ALTER TABLE "quality_qualityaudit" ADD CONSTRAINT "quality_qualityaudit_created_by_id_4c123413_fk_accounts_user_id" FOREIGN KEY ("created_by_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "quality_qualityaudit_date_72cb456b" ON "quality_qualityaudit" ("date");
CREATE INDEX "quality_qualityaudit_created_by_id_4c123413" ON "quality_qualityaudit" ("created_by_id");
ALTER TABLE "quality_qualitytest" ADD CONSTRAINT "quality_qualitytest_batch_id_d3f1d465_fk_productio" FOREIGN KEY ("batch_id") REFERENCES "production_productionbatch" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "quality_qualitytest" ADD CONSTRAINT "quality_qualitytest_tested_by_id_5ffa7872_fk_accounts_user_id" FOREIGN KEY ("tested_by_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "quality_qualitytest_test_date_766130ab" ON "quality_qualitytest" ("test_date");
CREATE INDEX "quality_qualitytest_result_1a8d98b3" ON "quality_qualitytest" ("result");
CREATE INDEX "quality_qualitytest_result_1a8d98b3_like" ON "quality_qualitytest" ("result" varchar_pattern_ops);
CREATE INDEX "quality_qualitytest_batch_id_d3f1d465" ON "quality_qualitytest" ("batch_id");
CREATE INDEX "quality_qualitytest_tested_by_id_5ffa7872" ON "quality_qualitytest" ("tested_by_id");
ALTER TABLE "quality_qualitystandard" ADD CONSTRAINT "quality_qualitystand_product_id_3515ec69_fk_inventory" FOREIGN KEY ("product_id") REFERENCES "inventory_product" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "quality_qualitystandard_product_id_3515ec69" ON "quality_qualitystandard" ("product_id");
CREATE TABLE "purchase_rawmaterial" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "material_code" varchar(20) NOT NULL UNIQUE, "name" varchar(120) NOT NULL UNIQUE, "category" varchar(12) NOT NULL, "unit" varchar(4) NOT NULL, "current_stock" numeric(12, 3) NOT NULL, "minimum_stock" numeric(12, 3) NOT NULL, "reorder_level" numeric(12, 3) NOT NULL, "purchase_price" numeric(12, 2) NULL, "status" varchar(10) NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL);
CREATE TABLE "purchase_purchase" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "purchase_number" varchar(20) NOT NULL UNIQUE, "quantity" numeric(12, 3) NOT NULL, "unit" varchar(4) NOT NULL, "unit_price" numeric(12, 2) NOT NULL, "discount_pct" numeric(5, 2) NOT NULL, "gst_pct" numeric(5, 2) NOT NULL, "subtotal" numeric(14, 2) NOT NULL, "discount_amount" numeric(14, 2) NOT NULL, "gst_amount" numeric(14, 2) NOT NULL, "total_amount" numeric(14, 2) NOT NULL, "purchase_date" date NOT NULL, "expected_receipt_date" date NULL, "payment_due_date" date NULL, "status" varchar(18) NOT NULL, "received_quantity" numeric(12, 3) NOT NULL, "returned_amount" numeric(14, 2) NOT NULL, "paid_amount" numeric(14, 2) NOT NULL, "notes" varchar(500) NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "created_by_id" bigint NULL, "product_id" bigint NULL, "material_id" bigint NULL);
CREATE TABLE "purchase_supplier" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "supplier_code" varchar(20) NOT NULL UNIQUE, "name" varchar(150) NOT NULL UNIQUE, "company_name" varchar(200) NOT NULL, "contact_person" varchar(120) NOT NULL, "phone" varchar(20) NOT NULL, "email" varchar(254) NOT NULL, "address" text NOT NULL, "city" varchar(80) NOT NULL, "state" varchar(80) NOT NULL, "gstin" varchar(15) NOT NULL, "payment_terms" varchar(120) NOT NULL, "credit_days" smallint NULL CHECK ("credit_days" >= 0), "status" varchar(10) NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "created_by_id" bigint NULL);
ALTER TABLE "purchase_rawmaterial" ADD COLUMN "supplier_id" bigint NULL CONSTRAINT "purchase_rawmaterial_supplier_id_917eb8ad_fk_purchase_" REFERENCES "purchase_supplier"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "purchase_rawmaterial_supplier_id_917eb8ad_fk_purchase_" IMMEDIATE;
CREATE TABLE "purchase_purchasereturn" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "return_number" varchar(20) NOT NULL UNIQUE, "quantity" numeric(12, 3) NOT NULL, "unit" varchar(4) NOT NULL, "return_date" date NOT NULL, "reason" varchar(10) NOT NULL, "amount" numeric(14, 2) NOT NULL, "status" varchar(10) NOT NULL, "remarks" varchar(500) NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "created_by_id" bigint NULL, "product_id" bigint NULL, "purchase_id" bigint NULL, "material_id" bigint NULL, "supplier_id" bigint NOT NULL);
ALTER TABLE "purchase_purchase" ADD COLUMN "supplier_id" bigint NOT NULL CONSTRAINT "purchase_purchase_supplier_id_e590af3a_fk_purchase_supplier_id" REFERENCES "purchase_supplier"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "purchase_purchase_supplier_id_e590af3a_fk_purchase_supplier_id" IMMEDIATE;
CREATE TABLE "purchase_supplierpayment" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "payment_number" varchar(20) NOT NULL UNIQUE, "amount" numeric(14, 2) NOT NULL, "payment_date" date NOT NULL, "payment_method" varchar(13) NOT NULL, "transaction_reference" varchar(80) NOT NULL, "status" varchar(14) NOT NULL, "notes" varchar(500) NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "created_by_id" bigint NULL, "purchase_id" bigint NULL, "supplier_id" bigint NOT NULL);
CREATE TABLE "purchase_goodsreceipt" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "grn_number" varchar(20) NOT NULL UNIQUE, "received_date" date NOT NULL, "received_quantity" numeric(12, 3) NOT NULL, "damaged_quantity" numeric(12, 3) NOT NULL, "accepted_quantity" numeric(12, 3) NOT NULL, "quality_status" varchar(8) NOT NULL, "remarks" varchar(500) NOT NULL, "stock_recorded" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "created_by_id" bigint NULL, "purchase_id" bigint NOT NULL, CONSTRAINT "grn_received_positive" CHECK ("received_quantity" > 0), CONSTRAINT "grn_damaged_within_received" CHECK ("damaged_quantity" <= ("received_quantity")), CONSTRAINT "grn_accepted_within_good" CHECK ("accepted_quantity" <= ("received_quantity" - "damaged_quantity")));
CREATE TABLE "purchase_materialmovement" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "type" varchar(3) NOT NULL, "source" varchar(15) NOT NULL, "quantity" numeric(12, 3) NOT NULL, "date" date NOT NULL, "reference" varchar(50) NOT NULL, "note" varchar(255) NOT NULL, "created_at" timestamp with time zone NOT NULL, "created_by_id" bigint NULL, "material_id" bigint NOT NULL, CONSTRAINT "raw_material_movement_positive" CHECK ("quantity" > 0));
ALTER TABLE "purchase_rawmaterial" ADD CONSTRAINT "raw_material_stock_not_negative" CHECK ("current_stock" >= 0);
ALTER TABLE "purchase_rawmaterial" ADD CONSTRAINT "material_reorder_at_or_above_min" CHECK ("reorder_level" >= ("minimum_stock"));
ALTER TABLE "purchase_purchasereturn" ADD CONSTRAINT "purchase_return_one_item" CHECK ((("material_id" IS NOT NULL AND "product_id" IS NULL) OR ("material_id" IS NULL AND "product_id" IS NOT NULL)));
ALTER TABLE "purchase_purchasereturn" ADD CONSTRAINT "purchase_return_quantity_positive" CHECK ("quantity" > 0);
ALTER TABLE "purchase_purchase" ADD CONSTRAINT "purchase_one_item" CHECK ((("material_id" IS NOT NULL AND "product_id" IS NULL) OR ("material_id" IS NULL AND "product_id" IS NOT NULL)));
ALTER TABLE "purchase_purchase" ADD CONSTRAINT "purchase_quantity_positive" CHECK ("quantity" > 0);
ALTER TABLE "purchase_purchase" ADD CONSTRAINT "purchase_receipt_after_date" CHECK (("expected_receipt_date" IS NULL OR "expected_receipt_date" >= ("purchase_date")));
ALTER TABLE "purchase_supplierpayment" ADD CONSTRAINT "supplier_payment_positive" CHECK ("amount" > 0);
CREATE INDEX "purchase_rawmaterial_material_code_2833c42b_like" ON "purchase_rawmaterial" ("material_code" varchar_pattern_ops);
CREATE INDEX "purchase_rawmaterial_name_34496568_like" ON "purchase_rawmaterial" ("name" varchar_pattern_ops);
CREATE INDEX "purchase_rawmaterial_category_35465f24" ON "purchase_rawmaterial" ("category");
CREATE INDEX "purchase_rawmaterial_category_35465f24_like" ON "purchase_rawmaterial" ("category" varchar_pattern_ops);
CREATE INDEX "purchase_rawmaterial_status_c0c8aac0" ON "purchase_rawmaterial" ("status");
CREATE INDEX "purchase_rawmaterial_status_c0c8aac0_like" ON "purchase_rawmaterial" ("status" varchar_pattern_ops);
ALTER TABLE "purchase_purchase" ADD CONSTRAINT "purchase_purchase_created_by_id_2b497688_fk_accounts_user_id" FOREIGN KEY ("created_by_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "purchase_purchase" ADD CONSTRAINT "purchase_purchase_product_id_a33babca_fk_inventory_product_id" FOREIGN KEY ("product_id") REFERENCES "inventory_product" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "purchase_purchase" ADD CONSTRAINT "purchase_purchase_material_id_9524fbba_fk_purchase_" FOREIGN KEY ("material_id") REFERENCES "purchase_rawmaterial" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "purchase_purchase_purchase_number_ad2eb11e_like" ON "purchase_purchase" ("purchase_number" varchar_pattern_ops);
CREATE INDEX "purchase_purchase_purchase_date_19c58046" ON "purchase_purchase" ("purchase_date");
CREATE INDEX "purchase_purchase_status_602cadfc" ON "purchase_purchase" ("status");
CREATE INDEX "purchase_purchase_status_602cadfc_like" ON "purchase_purchase" ("status" varchar_pattern_ops);
CREATE INDEX "purchase_purchase_created_by_id_2b497688" ON "purchase_purchase" ("created_by_id");
CREATE INDEX "purchase_purchase_product_id_a33babca" ON "purchase_purchase" ("product_id");
CREATE INDEX "purchase_purchase_material_id_9524fbba" ON "purchase_purchase" ("material_id");
ALTER TABLE "purchase_supplier" ADD CONSTRAINT "purchase_supplier_created_by_id_1a7d460a_fk_accounts_user_id" FOREIGN KEY ("created_by_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "purchase_supplier_supplier_code_79d1c151_like" ON "purchase_supplier" ("supplier_code" varchar_pattern_ops);
CREATE INDEX "purchase_supplier_name_a6d8a09a_like" ON "purchase_supplier" ("name" varchar_pattern_ops);
CREATE INDEX "purchase_supplier_city_49d42863" ON "purchase_supplier" ("city");
CREATE INDEX "purchase_supplier_city_49d42863_like" ON "purchase_supplier" ("city" varchar_pattern_ops);
CREATE INDEX "purchase_supplier_status_64c05768" ON "purchase_supplier" ("status");
CREATE INDEX "purchase_supplier_status_64c05768_like" ON "purchase_supplier" ("status" varchar_pattern_ops);
CREATE INDEX "purchase_supplier_created_at_28f2059b" ON "purchase_supplier" ("created_at");
CREATE INDEX "purchase_supplier_created_by_id_1a7d460a" ON "purchase_supplier" ("created_by_id");
CREATE INDEX "purchase_rawmaterial_supplier_id_917eb8ad" ON "purchase_rawmaterial" ("supplier_id");
ALTER TABLE "purchase_purchasereturn" ADD CONSTRAINT "purchase_purchaseret_created_by_id_ffec554c_fk_accounts_" FOREIGN KEY ("created_by_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "purchase_purchasereturn" ADD CONSTRAINT "purchase_purchaseret_product_id_57e6c5b4_fk_inventory" FOREIGN KEY ("product_id") REFERENCES "inventory_product" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "purchase_purchasereturn" ADD CONSTRAINT "purchase_purchaseret_purchase_id_d4019c38_fk_purchase_" FOREIGN KEY ("purchase_id") REFERENCES "purchase_purchase" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "purchase_purchasereturn" ADD CONSTRAINT "purchase_purchaseret_material_id_5d2a1eac_fk_purchase_" FOREIGN KEY ("material_id") REFERENCES "purchase_rawmaterial" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "purchase_purchasereturn" ADD CONSTRAINT "purchase_purchaseret_supplier_id_b2deab0a_fk_purchase_" FOREIGN KEY ("supplier_id") REFERENCES "purchase_supplier" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "purchase_purchasereturn_return_number_0b33f042_like" ON "purchase_purchasereturn" ("return_number" varchar_pattern_ops);
CREATE INDEX "purchase_purchasereturn_return_date_c74fb647" ON "purchase_purchasereturn" ("return_date");
CREATE INDEX "purchase_purchasereturn_status_188c1e55" ON "purchase_purchasereturn" ("status");
CREATE INDEX "purchase_purchasereturn_status_188c1e55_like" ON "purchase_purchasereturn" ("status" varchar_pattern_ops);
CREATE INDEX "purchase_purchasereturn_created_by_id_ffec554c" ON "purchase_purchasereturn" ("created_by_id");
CREATE INDEX "purchase_purchasereturn_product_id_57e6c5b4" ON "purchase_purchasereturn" ("product_id");
CREATE INDEX "purchase_purchasereturn_purchase_id_d4019c38" ON "purchase_purchasereturn" ("purchase_id");
CREATE INDEX "purchase_purchasereturn_material_id_5d2a1eac" ON "purchase_purchasereturn" ("material_id");
CREATE INDEX "purchase_purchasereturn_supplier_id_b2deab0a" ON "purchase_purchasereturn" ("supplier_id");
CREATE INDEX "purchase_purchase_supplier_id_e590af3a" ON "purchase_purchase" ("supplier_id");
ALTER TABLE "purchase_supplierpayment" ADD CONSTRAINT "purchase_supplierpay_created_by_id_9f0d1e49_fk_accounts_" FOREIGN KEY ("created_by_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "purchase_supplierpayment" ADD CONSTRAINT "purchase_supplierpay_purchase_id_cdd5318c_fk_purchase_" FOREIGN KEY ("purchase_id") REFERENCES "purchase_purchase" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "purchase_supplierpayment" ADD CONSTRAINT "purchase_supplierpay_supplier_id_01457bc7_fk_purchase_" FOREIGN KEY ("supplier_id") REFERENCES "purchase_supplier" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "purchase_supplierpayment_payment_number_8b3387ac_like" ON "purchase_supplierpayment" ("payment_number" varchar_pattern_ops);
CREATE INDEX "purchase_supplierpayment_payment_date_0ba449e2" ON "purchase_supplierpayment" ("payment_date");
CREATE INDEX "purchase_supplierpayment_status_3e8a47bf" ON "purchase_supplierpayment" ("status");
CREATE INDEX "purchase_supplierpayment_status_3e8a47bf_like" ON "purchase_supplierpayment" ("status" varchar_pattern_ops);
CREATE INDEX "purchase_supplierpayment_created_by_id_9f0d1e49" ON "purchase_supplierpayment" ("created_by_id");
CREATE INDEX "purchase_supplierpayment_purchase_id_cdd5318c" ON "purchase_supplierpayment" ("purchase_id");
CREATE INDEX "purchase_supplierpayment_supplier_id_01457bc7" ON "purchase_supplierpayment" ("supplier_id");
ALTER TABLE "purchase_goodsreceipt" ADD CONSTRAINT "purchase_goodsreceip_created_by_id_763272f5_fk_accounts_" FOREIGN KEY ("created_by_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "purchase_goodsreceipt" ADD CONSTRAINT "purchase_goodsreceip_purchase_id_55384617_fk_purchase_" FOREIGN KEY ("purchase_id") REFERENCES "purchase_purchase" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "purchase_goodsreceipt_grn_number_b8c31f3b_like" ON "purchase_goodsreceipt" ("grn_number" varchar_pattern_ops);
CREATE INDEX "purchase_goodsreceipt_received_date_4d570668" ON "purchase_goodsreceipt" ("received_date");
CREATE INDEX "purchase_goodsreceipt_quality_status_91f48aec" ON "purchase_goodsreceipt" ("quality_status");
CREATE INDEX "purchase_goodsreceipt_quality_status_91f48aec_like" ON "purchase_goodsreceipt" ("quality_status" varchar_pattern_ops);
CREATE INDEX "purchase_goodsreceipt_created_by_id_763272f5" ON "purchase_goodsreceipt" ("created_by_id");
CREATE INDEX "purchase_goodsreceipt_purchase_id_55384617" ON "purchase_goodsreceipt" ("purchase_id");
ALTER TABLE "purchase_materialmovement" ADD CONSTRAINT "purchase_materialmov_created_by_id_81b6a02a_fk_accounts_" FOREIGN KEY ("created_by_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "purchase_materialmovement" ADD CONSTRAINT "purchase_materialmov_material_id_a5192364_fk_purchase_" FOREIGN KEY ("material_id") REFERENCES "purchase_rawmaterial" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "purchase_materialmovement_date_f56cf9b4" ON "purchase_materialmovement" ("date");
CREATE INDEX "purchase_materialmovement_created_by_id_81b6a02a" ON "purchase_materialmovement" ("created_by_id");
CREATE INDEX "purchase_materialmovement_material_id_a5192364" ON "purchase_materialmovement" ("material_id");
ALTER TABLE "quality_qualitytest" DROP COLUMN "batch_id";
ALTER TABLE "quality_qualitytest" ADD COLUMN "batch_number" varchar(40) DEFAULT '' NOT NULL;
ALTER TABLE "quality_qualitytest" ALTER COLUMN "batch_number" DROP DEFAULT;
ALTER TABLE "quality_qualitytest" ADD COLUMN "goods_receipt_id" bigint NULL CONSTRAINT "quality_qualitytest_goods_receipt_id_6d48e4ff_fk_purchase_" REFERENCES "purchase_goodsreceipt"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "quality_qualitytest_goods_receipt_id_6d48e4ff_fk_purchase_" IMMEDIATE;
ALTER TABLE "quality_qualitytest" ADD COLUMN "material_id" bigint NULL CONSTRAINT "quality_qualitytest_material_id_ba10e424_fk_purchase_" REFERENCES "purchase_rawmaterial"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "quality_qualitytest_material_id_ba10e424_fk_purchase_" IMMEDIATE;
ALTER TABLE "quality_qualitytest" ADD COLUMN "product_id" bigint NULL CONSTRAINT "quality_qualitytest_product_id_fa1bdce6_fk_inventory_product_id" REFERENCES "inventory_product"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "quality_qualitytest_product_id_fa1bdce6_fk_inventory_product_id" IMMEDIATE;
ALTER TABLE "quality_qualitytest" ADD CONSTRAINT "quality_test_one_item" CHECK ((("material_id" IS NULL AND "product_id" IS NOT NULL) OR ("material_id" IS NOT NULL AND "product_id" IS NULL)));
CREATE INDEX "quality_qualitytest_batch_number_7a616b10" ON "quality_qualitytest" ("batch_number");
CREATE INDEX "quality_qualitytest_batch_number_7a616b10_like" ON "quality_qualitytest" ("batch_number" varchar_pattern_ops);
CREATE INDEX "quality_qualitytest_goods_receipt_id_6d48e4ff" ON "quality_qualitytest" ("goods_receipt_id");
CREATE INDEX "quality_qualitytest_material_id_ba10e424" ON "quality_qualitytest" ("material_id");
CREATE INDEX "quality_qualitytest_product_id_fa1bdce6" ON "quality_qualitytest" ("product_id");
ALTER TABLE "production_productionbatch" DROP CONSTRAINT "batch_due_after_start";
ALTER TABLE "production_productionbatch" DROP CONSTRAINT "batch_quantity_positive";
ALTER TABLE "production_productionbatch" DROP COLUMN "created_by_id";
ALTER TABLE "production_productionbatch" DROP COLUMN "line_id";
ALTER TABLE "production_productionbatch" DROP COLUMN "product_id";
DROP TABLE "production_productionline" CASCADE;
DROP TABLE "production_productionbatch" CASCADE;
CREATE TABLE "reports_report" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(150) NOT NULL, "type" varchar(15) NOT NULL, "range" varchar(20) NOT NULL, "range_label" varchar(60) NOT NULL, "format" varchar(4) NOT NULL, "status" varchar(10) NOT NULL, "file" varchar(100) NOT NULL, "error" varchar(500) NOT NULL, "created_at" timestamp with time zone NOT NULL, "created_by_id" bigint NULL);
ALTER TABLE "reports_report" ADD CONSTRAINT "reports_report_created_by_id_e9adac24_fk_accounts_user_id" FOREIGN KEY ("created_by_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "reports_report_type_e8558091" ON "reports_report" ("type");
CREATE INDEX "reports_report_type_e8558091_like" ON "reports_report" ("type" varchar_pattern_ops);
CREATE INDEX "reports_report_created_at_4f9096d5" ON "reports_report" ("created_at");
CREATE INDEX "reports_report_created_by_id_e9adac24" ON "reports_report" ("created_by_id");
CREATE TABLE "sales_salesorder" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "order_number" varchar(20) NOT NULL UNIQUE, "order_date" date NOT NULL, "status" varchar(12) NOT NULL, "total_amount" numeric(14, 2) NOT NULL, "notes" varchar(500) NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "created_by_id" bigint NULL, "customer_id" bigint NOT NULL);
CREATE TABLE "sales_salesorderitem" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "quantity_kg" numeric(12, 3) NOT NULL, "unit_price" numeric(10, 2) NOT NULL, "amount" numeric(14, 2) NOT NULL, "order_id" bigint NOT NULL, "product_id" bigint NOT NULL, CONSTRAINT "order_item_quantity_positive" CHECK ("quantity_kg" > 0), CONSTRAINT "unique_product_per_order" UNIQUE ("order_id", "product_id"));
ALTER TABLE "sales_salesorder" ADD CONSTRAINT "sales_salesorder_created_by_id_0700fb7b_fk_accounts_user_id" FOREIGN KEY ("created_by_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sales_salesorder" ADD CONSTRAINT "sales_salesorder_customer_id_e8577187_fk_customers_customer_id" FOREIGN KEY ("customer_id") REFERENCES "customers_customer" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "sales_salesorder_order_number_6cb21724_like" ON "sales_salesorder" ("order_number" varchar_pattern_ops);
CREATE INDEX "sales_salesorder_order_date_c6240eec" ON "sales_salesorder" ("order_date");
CREATE INDEX "sales_salesorder_status_0cbc612a" ON "sales_salesorder" ("status");
CREATE INDEX "sales_salesorder_status_0cbc612a_like" ON "sales_salesorder" ("status" varchar_pattern_ops);
CREATE INDEX "sales_salesorder_created_by_id_0700fb7b" ON "sales_salesorder" ("created_by_id");
CREATE INDEX "sales_salesorder_customer_id_e8577187" ON "sales_salesorder" ("customer_id");
ALTER TABLE "sales_salesorderitem" ADD CONSTRAINT "sales_salesorderitem_order_id_51c29b8a_fk_sales_salesorder_id" FOREIGN KEY ("order_id") REFERENCES "sales_salesorder" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sales_salesorderitem" ADD CONSTRAINT "sales_salesorderitem_product_id_75dab6e4_fk_inventory" FOREIGN KEY ("product_id") REFERENCES "inventory_product" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "sales_salesorderitem_order_id_51c29b8a" ON "sales_salesorderitem" ("order_id");
CREATE INDEX "sales_salesorderitem_product_id_75dab6e4" ON "sales_salesorderitem" ("product_id");
ALTER TABLE "sales_salesorder" ADD COLUMN "discount_amount" numeric(14, 2) DEFAULT 0 NOT NULL;
ALTER TABLE "sales_salesorder" ALTER COLUMN "discount_amount" DROP DEFAULT;
ALTER TABLE "sales_salesorder" ADD COLUMN "gst_amount" numeric(14, 2) DEFAULT 0 NOT NULL;
ALTER TABLE "sales_salesorder" ALTER COLUMN "gst_amount" DROP DEFAULT;
ALTER TABLE "sales_salesorder" ADD COLUMN "subtotal" numeric(14, 2) DEFAULT 0 NOT NULL;
ALTER TABLE "sales_salesorder" ALTER COLUMN "subtotal" DROP DEFAULT;
ALTER TABLE "sales_salesorderitem" ADD COLUMN "discount_amount" numeric(14, 2) DEFAULT 0 NOT NULL;
ALTER TABLE "sales_salesorderitem" ALTER COLUMN "discount_amount" DROP DEFAULT;
ALTER TABLE "sales_salesorderitem" ADD COLUMN "discount_pct" numeric(5, 2) DEFAULT 0 NOT NULL;
ALTER TABLE "sales_salesorderitem" ALTER COLUMN "discount_pct" DROP DEFAULT;
ALTER TABLE "sales_salesorderitem" ADD COLUMN "gst_amount" numeric(14, 2) DEFAULT 0 NOT NULL;
ALTER TABLE "sales_salesorderitem" ALTER COLUMN "gst_amount" DROP DEFAULT;
ALTER TABLE "sales_salesorderitem" ADD COLUMN "gst_pct" numeric(5, 2) DEFAULT 0 NOT NULL;
ALTER TABLE "sales_salesorderitem" ALTER COLUMN "gst_pct" DROP DEFAULT;
ALTER TABLE "sales_salesorderitem" ADD COLUMN "subtotal" numeric(14, 2) DEFAULT 0 NOT NULL;
ALTER TABLE "sales_salesorderitem" ALTER COLUMN "subtotal" DROP DEFAULT;
ALTER TABLE "sales_salesorderitem" ADD COLUMN "total" numeric(14, 2) DEFAULT 0 NOT NULL;
ALTER TABLE "sales_salesorderitem" ALTER COLUMN "total" DROP DEFAULT;
CREATE TABLE "sales_salesquotation" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "subtotal" numeric(14, 2) NOT NULL, "discount_amount" numeric(14, 2) NOT NULL, "gst_amount" numeric(14, 2) NOT NULL, "customer_name" varchar(150) NOT NULL, "company_name" varchar(200) NOT NULL, "billing_address" text NOT NULL, "shipping_address" text NOT NULL, "phone" varchar(20) NOT NULL, "email" varchar(254) NOT NULL, "gstin" varchar(15) NOT NULL, "quotation_number" varchar(20) NOT NULL UNIQUE, "quotation_date" date NOT NULL, "valid_until" date NOT NULL, "status" varchar(10) NOT NULL, "grand_total" numeric(14, 2) NOT NULL, "payment_terms" varchar(255) NOT NULL, "delivery_terms" varchar(255) NOT NULL, "notes" text NOT NULL, "terms_conditions" text NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "created_by_id" bigint NULL, "customer_id" bigint NULL);
CREATE TABLE "sales_salesinvoice" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "subtotal" numeric(14, 2) NOT NULL, "discount_amount" numeric(14, 2) NOT NULL, "gst_amount" numeric(14, 2) NOT NULL, "customer_name" varchar(150) NOT NULL, "company_name" varchar(200) NOT NULL, "billing_address" text NOT NULL, "shipping_address" text NOT NULL, "phone" varchar(20) NOT NULL, "email" varchar(254) NOT NULL, "gstin" varchar(15) NOT NULL, "invoice_number" varchar(20) NOT NULL UNIQUE, "invoice_date" date NOT NULL, "due_date" date NULL, "status" varchar(10) NOT NULL, "grand_total" numeric(14, 2) NOT NULL, "amount_paid" numeric(14, 2) NOT NULL, "credited_amount" numeric(14, 2) NOT NULL, "stock_moved" boolean NOT NULL, "payment_terms" varchar(255) NOT NULL, "notes" text NOT NULL, "terms_conditions" text NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "created_by_id" bigint NULL, "customer_id" bigint NOT NULL, "sales_order_id" bigint NULL, "quotation_id" bigint NULL);
CREATE TABLE "sales_quotationstatuschange" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "from_status" varchar(10) NOT NULL, "to_status" varchar(10) NOT NULL, "note" varchar(255) NOT NULL, "changed_at" timestamp with time zone NOT NULL, "changed_by_id" bigint NULL, "quotation_id" bigint NOT NULL);
ALTER TABLE "sales_salesorder" ADD COLUMN "quotation_id" bigint NULL UNIQUE CONSTRAINT "sales_salesorder_quotation_id_2baab49a_fk_sales_sal" REFERENCES "sales_salesquotation"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "sales_salesorder_quotation_id_2baab49a_fk_sales_sal" IMMEDIATE;
CREATE TABLE "sales_salesquotationitem" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "quantity_kg" numeric(12, 3) NOT NULL, "unit_price" numeric(10, 2) NOT NULL, "discount_pct" numeric(5, 2) NOT NULL, "gst_pct" numeric(5, 2) NOT NULL, "subtotal" numeric(14, 2) NOT NULL, "discount_amount" numeric(14, 2) NOT NULL, "amount" numeric(14, 2) NOT NULL, "gst_amount" numeric(14, 2) NOT NULL, "total" numeric(14, 2) NOT NULL, "product_id" bigint NOT NULL, "quotation_id" bigint NOT NULL);
CREATE TABLE "sales_salesreturn" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "return_number" varchar(20) NOT NULL UNIQUE, "quantity_kg" numeric(12, 3) NOT NULL, "return_date" date NOT NULL, "reason" varchar(10) NOT NULL, "amount" numeric(14, 2) NOT NULL, "restock" boolean NOT NULL, "status" varchar(10) NOT NULL, "remarks" varchar(500) NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "created_by_id" bigint NULL, "customer_id" bigint NOT NULL, "invoice_id" bigint NOT NULL, "product_id" bigint NOT NULL);
CREATE TABLE "sales_salesinvoiceitem" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "quantity_kg" numeric(12, 3) NOT NULL, "unit_price" numeric(10, 2) NOT NULL, "discount_pct" numeric(5, 2) NOT NULL, "gst_pct" numeric(5, 2) NOT NULL, "subtotal" numeric(14, 2) NOT NULL, "discount_amount" numeric(14, 2) NOT NULL, "amount" numeric(14, 2) NOT NULL, "gst_amount" numeric(14, 2) NOT NULL, "total" numeric(14, 2) NOT NULL, "invoice_id" bigint NOT NULL, "product_id" bigint NOT NULL, CONSTRAINT "unique_product_per_invoice" UNIQUE ("invoice_id", "product_id"));
CREATE TABLE "sales_salespayment" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "receipt_number" varchar(20) NOT NULL UNIQUE, "amount" numeric(14, 2) NOT NULL, "payment_date" date NOT NULL, "payment_method" varchar(13) NOT NULL, "reference" varchar(80) NOT NULL, "status" varchar(10) NOT NULL, "notes" varchar(500) NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "created_by_id" bigint NULL, "customer_id" bigint NOT NULL, "invoice_id" bigint NOT NULL, CONSTRAINT "sales_payment_positive" CHECK ("amount" > 0));
ALTER TABLE "sales_salesquotation" ADD CONSTRAINT "quotation_valid_after_date" CHECK ("valid_until" >= ("quotation_date"));
ALTER TABLE "sales_salesinvoice" ADD CONSTRAINT "invoice_due_after_date" CHECK (("due_date" IS NULL OR "due_date" >= ("invoice_date")));
ALTER TABLE "sales_salesquotationitem" ADD CONSTRAINT "unique_product_per_quotation" UNIQUE ("quotation_id", "product_id");
ALTER TABLE "sales_salesreturn" ADD CONSTRAINT "sales_return_quantity_positive" CHECK ("quantity_kg" > 0);
ALTER TABLE "sales_salesquotation" ADD CONSTRAINT "sales_salesquotation_created_by_id_c152331c_fk_accounts_user_id" FOREIGN KEY ("created_by_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sales_salesquotation" ADD CONSTRAINT "sales_salesquotation_customer_id_96edd554_fk_customers" FOREIGN KEY ("customer_id") REFERENCES "customers_customer" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "sales_salesquotation_quotation_number_29aa3dc9_like" ON "sales_salesquotation" ("quotation_number" varchar_pattern_ops);
CREATE INDEX "sales_salesquotation_quotation_date_572449d6" ON "sales_salesquotation" ("quotation_date");
CREATE INDEX "sales_salesquotation_status_5b85bb35" ON "sales_salesquotation" ("status");
CREATE INDEX "sales_salesquotation_status_5b85bb35_like" ON "sales_salesquotation" ("status" varchar_pattern_ops);
CREATE INDEX "sales_salesquotation_created_by_id_c152331c" ON "sales_salesquotation" ("created_by_id");
CREATE INDEX "sales_salesquotation_customer_id_96edd554" ON "sales_salesquotation" ("customer_id");
ALTER TABLE "sales_salesinvoice" ADD CONSTRAINT "sales_salesinvoice_created_by_id_2980679a_fk_accounts_user_id" FOREIGN KEY ("created_by_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sales_salesinvoice" ADD CONSTRAINT "sales_salesinvoice_customer_id_5ba2c897_fk_customers" FOREIGN KEY ("customer_id") REFERENCES "customers_customer" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sales_salesinvoice" ADD CONSTRAINT "sales_salesinvoice_sales_order_id_2bc957c9_fk_sales_sal" FOREIGN KEY ("sales_order_id") REFERENCES "sales_salesorder" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sales_salesinvoice" ADD CONSTRAINT "sales_salesinvoice_quotation_id_46ae2787_fk_sales_sal" FOREIGN KEY ("quotation_id") REFERENCES "sales_salesquotation" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "sales_salesinvoice_invoice_number_17637ab4_like" ON "sales_salesinvoice" ("invoice_number" varchar_pattern_ops);
CREATE INDEX "sales_salesinvoice_invoice_date_a2ebb7e2" ON "sales_salesinvoice" ("invoice_date");
CREATE INDEX "sales_salesinvoice_status_4d372a61" ON "sales_salesinvoice" ("status");
CREATE INDEX "sales_salesinvoice_status_4d372a61_like" ON "sales_salesinvoice" ("status" varchar_pattern_ops);
CREATE INDEX "sales_salesinvoice_created_by_id_2980679a" ON "sales_salesinvoice" ("created_by_id");
CREATE INDEX "sales_salesinvoice_customer_id_5ba2c897" ON "sales_salesinvoice" ("customer_id");
CREATE INDEX "sales_salesinvoice_sales_order_id_2bc957c9" ON "sales_salesinvoice" ("sales_order_id");
CREATE INDEX "sales_salesinvoice_quotation_id_46ae2787" ON "sales_salesinvoice" ("quotation_id");
ALTER TABLE "sales_quotationstatuschange" ADD CONSTRAINT "sales_quotationstatu_changed_by_id_79040248_fk_accounts_" FOREIGN KEY ("changed_by_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sales_quotationstatuschange" ADD CONSTRAINT "sales_quotationstatu_quotation_id_c1348e94_fk_sales_sal" FOREIGN KEY ("quotation_id") REFERENCES "sales_salesquotation" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "sales_quotationstatuschange_changed_by_id_79040248" ON "sales_quotationstatuschange" ("changed_by_id");
CREATE INDEX "sales_quotationstatuschange_quotation_id_c1348e94" ON "sales_quotationstatuschange" ("quotation_id");
ALTER TABLE "sales_salesquotationitem" ADD CONSTRAINT "sales_salesquotation_product_id_1cf2d68c_fk_inventory" FOREIGN KEY ("product_id") REFERENCES "inventory_product" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sales_salesquotationitem" ADD CONSTRAINT "sales_salesquotation_quotation_id_4f653848_fk_sales_sal" FOREIGN KEY ("quotation_id") REFERENCES "sales_salesquotation" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "sales_salesquotationitem_product_id_1cf2d68c" ON "sales_salesquotationitem" ("product_id");
CREATE INDEX "sales_salesquotationitem_quotation_id_4f653848" ON "sales_salesquotationitem" ("quotation_id");
ALTER TABLE "sales_salesreturn" ADD CONSTRAINT "sales_salesreturn_created_by_id_7486ff06_fk_accounts_user_id" FOREIGN KEY ("created_by_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sales_salesreturn" ADD CONSTRAINT "sales_salesreturn_customer_id_55a6daab_fk_customers_customer_id" FOREIGN KEY ("customer_id") REFERENCES "customers_customer" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sales_salesreturn" ADD CONSTRAINT "sales_salesreturn_invoice_id_a8ef6a28_fk_sales_salesinvoice_id" FOREIGN KEY ("invoice_id") REFERENCES "sales_salesinvoice" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sales_salesreturn" ADD CONSTRAINT "sales_salesreturn_product_id_1ec6984a_fk_inventory_product_id" FOREIGN KEY ("product_id") REFERENCES "inventory_product" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "sales_salesreturn_return_number_0b38ffbc_like" ON "sales_salesreturn" ("return_number" varchar_pattern_ops);
CREATE INDEX "sales_salesreturn_return_date_a6a38a54" ON "sales_salesreturn" ("return_date");
CREATE INDEX "sales_salesreturn_status_25d70395" ON "sales_salesreturn" ("status");
CREATE INDEX "sales_salesreturn_status_25d70395_like" ON "sales_salesreturn" ("status" varchar_pattern_ops);
CREATE INDEX "sales_salesreturn_created_by_id_7486ff06" ON "sales_salesreturn" ("created_by_id");
CREATE INDEX "sales_salesreturn_customer_id_55a6daab" ON "sales_salesreturn" ("customer_id");
CREATE INDEX "sales_salesreturn_invoice_id_a8ef6a28" ON "sales_salesreturn" ("invoice_id");
CREATE INDEX "sales_salesreturn_product_id_1ec6984a" ON "sales_salesreturn" ("product_id");
ALTER TABLE "sales_salesinvoiceitem" ADD CONSTRAINT "sales_salesinvoiceit_invoice_id_885fc8ce_fk_sales_sal" FOREIGN KEY ("invoice_id") REFERENCES "sales_salesinvoice" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sales_salesinvoiceitem" ADD CONSTRAINT "sales_salesinvoiceit_product_id_773e7210_fk_inventory" FOREIGN KEY ("product_id") REFERENCES "inventory_product" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "sales_salesinvoiceitem_invoice_id_885fc8ce" ON "sales_salesinvoiceitem" ("invoice_id");
CREATE INDEX "sales_salesinvoiceitem_product_id_773e7210" ON "sales_salesinvoiceitem" ("product_id");
ALTER TABLE "sales_salespayment" ADD CONSTRAINT "sales_salespayment_created_by_id_dfd55a10_fk_accounts_user_id" FOREIGN KEY ("created_by_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sales_salespayment" ADD CONSTRAINT "sales_salespayment_customer_id_afd492d7_fk_customers" FOREIGN KEY ("customer_id") REFERENCES "customers_customer" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sales_salespayment" ADD CONSTRAINT "sales_salespayment_invoice_id_27c07bc9_fk_sales_salesinvoice_id" FOREIGN KEY ("invoice_id") REFERENCES "sales_salesinvoice" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "sales_salespayment_receipt_number_5ff9d0f0_like" ON "sales_salespayment" ("receipt_number" varchar_pattern_ops);
CREATE INDEX "sales_salespayment_payment_date_49b7e312" ON "sales_salespayment" ("payment_date");
CREATE INDEX "sales_salespayment_status_97fc668e" ON "sales_salespayment" ("status");
CREATE INDEX "sales_salespayment_status_97fc668e_like" ON "sales_salespayment" ("status" varchar_pattern_ops);
CREATE INDEX "sales_salespayment_created_by_id_dfd55a10" ON "sales_salespayment" ("created_by_id");
CREATE INDEX "sales_salespayment_customer_id_afd492d7" ON "sales_salespayment" ("customer_id");
CREATE INDEX "sales_salespayment_invoice_id_27c07bc9" ON "sales_salespayment" ("invoice_id");
CREATE TABLE "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" timestamp with time zone NOT NULL);
CREATE INDEX "django_session_session_key_c0390e0f_like" ON "django_session" ("session_key" varchar_pattern_ops);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE TABLE "supply_chain_supplier" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(150) NOT NULL UNIQUE, "city" varchar(80) NOT NULL, "contact_person" varchar(120) NOT NULL, "phone" varchar(20) NOT NULL, "email" varchar(254) NOT NULL, "is_active" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL);
CREATE TABLE "supply_chain_rawmaterial" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(120) NOT NULL UNIQUE, "stock_kg" numeric(12, 3) NOT NULL, "reorder_level_kg" numeric(12, 3) NOT NULL, "is_active" boolean NOT NULL, CONSTRAINT "material_stock_not_negative" CHECK ("stock_kg" >= 0));
CREATE TABLE "supply_chain_purchaseorder" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "po_number" varchar(20) NOT NULL UNIQUE, "quantity_kg" numeric(12, 3) NOT NULL, "rate_per_kg" numeric(10, 2) NULL, "order_date" date NOT NULL, "expected_delivery" date NOT NULL, "status" varchar(10) NOT NULL, "notes" varchar(500) NOT NULL, "created_at" timestamp with time zone NOT NULL, "created_by_id" bigint NULL, "material_id" bigint NOT NULL, "supplier_id" bigint NOT NULL);
CREATE TABLE "supply_chain_shipment" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "shipment_number" varchar(20) NOT NULL UNIQUE, "quantity_kg" numeric(12, 3) NOT NULL, "destination" varchar(120) NOT NULL, "dispatched_on" date NOT NULL, "eta" date NOT NULL, "delivered_on" date NULL, "status" varchar(12) NOT NULL, "quality_passed" boolean NULL, "stock_recorded" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "material_id" bigint NOT NULL, "purchase_order_id" bigint NULL, "supplier_id" bigint NOT NULL);
CREATE TABLE "supply_chain_materialmovement" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "type" varchar(3) NOT NULL, "quantity_kg" numeric(12, 3) NOT NULL, "date" date NOT NULL, "reference" varchar(50) NOT NULL, "note" varchar(255) NOT NULL, "created_at" timestamp with time zone NOT NULL, "created_by_id" bigint NULL, "material_id" bigint NOT NULL, CONSTRAINT "material_movement_positive" CHECK ("quantity_kg" > 0));
ALTER TABLE "supply_chain_purchaseorder" ADD CONSTRAINT "po_delivery_after_order" CHECK ("expected_delivery" >= ("order_date"));
CREATE INDEX "supply_chain_supplier_name_7b148e9f_like" ON "supply_chain_supplier" ("name" varchar_pattern_ops);
CREATE INDEX "supply_chain_rawmaterial_name_7052f880_like" ON "supply_chain_rawmaterial" ("name" varchar_pattern_ops);
ALTER TABLE "supply_chain_purchaseorder" ADD CONSTRAINT "supply_chain_purchas_created_by_id_821c7ddf_fk_accounts_" FOREIGN KEY ("created_by_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "supply_chain_purchaseorder" ADD CONSTRAINT "supply_chain_purchas_material_id_c9eb05ac_fk_supply_ch" FOREIGN KEY ("material_id") REFERENCES "supply_chain_rawmaterial" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "supply_chain_purchaseorder" ADD CONSTRAINT "supply_chain_purchas_supplier_id_411dacfa_fk_supply_ch" FOREIGN KEY ("supplier_id") REFERENCES "supply_chain_supplier" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "supply_chain_purchaseorder_po_number_d65f3370_like" ON "supply_chain_purchaseorder" ("po_number" varchar_pattern_ops);
CREATE INDEX "supply_chain_purchaseorder_order_date_e18c07f4" ON "supply_chain_purchaseorder" ("order_date");
CREATE INDEX "supply_chain_purchaseorder_status_63a8f7c4" ON "supply_chain_purchaseorder" ("status");
CREATE INDEX "supply_chain_purchaseorder_status_63a8f7c4_like" ON "supply_chain_purchaseorder" ("status" varchar_pattern_ops);
CREATE INDEX "supply_chain_purchaseorder_created_by_id_821c7ddf" ON "supply_chain_purchaseorder" ("created_by_id");
CREATE INDEX "supply_chain_purchaseorder_material_id_c9eb05ac" ON "supply_chain_purchaseorder" ("material_id");
CREATE INDEX "supply_chain_purchaseorder_supplier_id_411dacfa" ON "supply_chain_purchaseorder" ("supplier_id");
ALTER TABLE "supply_chain_shipment" ADD CONSTRAINT "supply_chain_shipmen_material_id_d30175f0_fk_supply_ch" FOREIGN KEY ("material_id") REFERENCES "supply_chain_rawmaterial" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "supply_chain_shipment" ADD CONSTRAINT "supply_chain_shipmen_purchase_order_id_a5b98fe6_fk_supply_ch" FOREIGN KEY ("purchase_order_id") REFERENCES "supply_chain_purchaseorder" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "supply_chain_shipment" ADD CONSTRAINT "supply_chain_shipmen_supplier_id_0af52adf_fk_supply_ch" FOREIGN KEY ("supplier_id") REFERENCES "supply_chain_supplier" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "supply_chain_shipment_shipment_number_205f21cb_like" ON "supply_chain_shipment" ("shipment_number" varchar_pattern_ops);
CREATE INDEX "supply_chain_shipment_status_97495848" ON "supply_chain_shipment" ("status");
CREATE INDEX "supply_chain_shipment_status_97495848_like" ON "supply_chain_shipment" ("status" varchar_pattern_ops);
CREATE INDEX "supply_chain_shipment_material_id_d30175f0" ON "supply_chain_shipment" ("material_id");
CREATE INDEX "supply_chain_shipment_purchase_order_id_a5b98fe6" ON "supply_chain_shipment" ("purchase_order_id");
CREATE INDEX "supply_chain_shipment_supplier_id_0af52adf" ON "supply_chain_shipment" ("supplier_id");
ALTER TABLE "supply_chain_materialmovement" ADD CONSTRAINT "supply_chain_materia_created_by_id_c8e8adc8_fk_accounts_" FOREIGN KEY ("created_by_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "supply_chain_materialmovement" ADD CONSTRAINT "supply_chain_materia_material_id_535083a8_fk_supply_ch" FOREIGN KEY ("material_id") REFERENCES "supply_chain_rawmaterial" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "supply_chain_materialmovement_date_e7f4ddf4" ON "supply_chain_materialmovement" ("date");
CREATE INDEX "supply_chain_materialmovement_created_by_id_c8e8adc8" ON "supply_chain_materialmovement" ("created_by_id");
CREATE INDEX "supply_chain_materialmovement_material_id_535083a8" ON "supply_chain_materialmovement" ("material_id");
DROP TABLE "supply_chain_shipment" CASCADE;
DROP TABLE "supply_chain_purchaseorder" CASCADE;
DROP TABLE "supply_chain_materialmovement" CASCADE;
DROP TABLE "supply_chain_rawmaterial" CASCADE;
DROP TABLE "supply_chain_supplier" CASCADE;
CREATE TABLE "supply_chain_shipment" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "shipment_number" varchar(20) NOT NULL UNIQUE, "quantity" numeric(12, 3) NOT NULL, "unit" varchar(4) NOT NULL, "destination" varchar(120) NOT NULL, "dispatched_on" date NOT NULL, "eta" date NOT NULL, "delivered_on" date NULL, "status" varchar(12) NOT NULL, "quality_passed" boolean NULL, "created_at" timestamp with time zone NOT NULL, "material_id" bigint NULL, "product_id" bigint NULL, "purchase_id" bigint NULL, "supplier_id" bigint NOT NULL, CONSTRAINT "shipment_one_item" CHECK ((("material_id" IS NOT NULL AND "product_id" IS NULL) OR ("material_id" IS NULL AND "product_id" IS NOT NULL))));
ALTER TABLE "supply_chain_shipment" ADD CONSTRAINT "supply_chain_shipmen_material_id_d30175f0_fk_purchase_" FOREIGN KEY ("material_id") REFERENCES "purchase_rawmaterial" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "supply_chain_shipment" ADD CONSTRAINT "supply_chain_shipmen_product_id_6335a5e8_fk_inventory" FOREIGN KEY ("product_id") REFERENCES "inventory_product" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "supply_chain_shipment" ADD CONSTRAINT "supply_chain_shipmen_purchase_id_dbaab89a_fk_purchase_" FOREIGN KEY ("purchase_id") REFERENCES "purchase_purchase" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "supply_chain_shipment" ADD CONSTRAINT "supply_chain_shipmen_supplier_id_0af52adf_fk_purchase_" FOREIGN KEY ("supplier_id") REFERENCES "purchase_supplier" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "supply_chain_shipment_shipment_number_205f21cb_like" ON "supply_chain_shipment" ("shipment_number" varchar_pattern_ops);
CREATE INDEX "supply_chain_shipment_status_97495848" ON "supply_chain_shipment" ("status");
CREATE INDEX "supply_chain_shipment_status_97495848_like" ON "supply_chain_shipment" ("status" varchar_pattern_ops);
CREATE INDEX "supply_chain_shipment_material_id_d30175f0" ON "supply_chain_shipment" ("material_id");
CREATE INDEX "supply_chain_shipment_product_id_6335a5e8" ON "supply_chain_shipment" ("product_id");
CREATE INDEX "supply_chain_shipment_purchase_id_dbaab89a" ON "supply_chain_shipment" ("purchase_id");
CREATE INDEX "supply_chain_shipment_supplier_id_0af52adf" ON "supply_chain_shipment" ("supplier_id");
CREATE TABLE "system_backupsettings" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "automatic" boolean NOT NULL, "retention_months" smallint NULL CHECK ("retention_months" >= 0), "updated_at" timestamp with time zone NOT NULL);
CREATE TABLE "system_companysettings" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "company_name" varchar(150) NOT NULL, "tagline" varchar(200) NOT NULL, "timezone" varchar(64) NOT NULL, "date_format" varchar(20) NOT NULL, "time_format" varchar(10) NOT NULL, "currency" varchar(3) NOT NULL, "language" varchar(10) NOT NULL, "legal_name" varchar(200) NOT NULL, "address" text NOT NULL, "email" varchar(254) NOT NULL, "phone" varchar(20) NOT NULL, "website" varchar(200) NOT NULL, "gstin" varchar(15) NOT NULL, "updated_at" timestamp with time zone NOT NULL);
CREATE TABLE "system_notificationpreference" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "key" varchar(40) NOT NULL UNIQUE, "enabled" boolean NOT NULL, "updated_at" timestamp with time zone NOT NULL);
CREATE TABLE "system_auditlog" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "action" varchar(200) NOT NULL, "target" varchar(200) NOT NULL, "ip" inet NULL, "created_at" timestamp with time zone NOT NULL, "user_id" bigint NULL);
CREATE TABLE "system_backuprun" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "started_at" timestamp with time zone NOT NULL, "finished_at" timestamp with time zone NULL, "status" varchar(10) NOT NULL, "file_name" varchar(255) NOT NULL, "size_bytes" bigint NULL, "error" text NOT NULL, "triggered_by_id" bigint NULL);
CREATE TABLE "system_notification" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "key" varchar(40) NOT NULL, "title" varchar(200) NOT NULL, "message" text NOT NULL, "type" varchar(10) NOT NULL, "link" varchar(200) NOT NULL, "read" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "user_id" bigint NOT NULL);
CREATE INDEX "system_notificationpreference_key_f7bad49a_like" ON "system_notificationpreference" ("key" varchar_pattern_ops);
ALTER TABLE "system_auditlog" ADD CONSTRAINT "system_auditlog_user_id_0ed6e420_fk_accounts_user_id" FOREIGN KEY ("user_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "system_auditlog_created_at_ee68f9ca" ON "system_auditlog" ("created_at");
CREATE INDEX "system_auditlog_user_id_0ed6e420" ON "system_auditlog" ("user_id");
ALTER TABLE "system_backuprun" ADD CONSTRAINT "system_backuprun_triggered_by_id_775ba94f_fk_accounts_user_id" FOREIGN KEY ("triggered_by_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "system_backuprun_triggered_by_id_775ba94f" ON "system_backuprun" ("triggered_by_id");
ALTER TABLE "system_notification" ADD CONSTRAINT "system_notification_user_id_2574db7e_fk_accounts_user_id" FOREIGN KEY ("user_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "system_notification_read_7717e72e" ON "system_notification" ("read");
CREATE INDEX "system_notification_created_at_97e6d615" ON "system_notification" ("created_at");
CREATE INDEX "system_notification_user_id_2574db7e" ON "system_notification" ("user_id");
CREATE INDEX "system_noti_user_id_4d9549_idx" ON "system_notification" ("user_id", "read");
CREATE TABLE "system_billingsettings" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "default_sales_gst_pct" numeric(5, 2) NULL, "default_purchase_gst_pct" numeric(5, 2) NULL, "quotation_validity_days" smallint NULL CHECK ("quotation_validity_days" >= 0), "quotation_payment_terms" varchar(255) NOT NULL, "quotation_delivery_terms" varchar(255) NOT NULL, "quotation_terms" text NOT NULL, "invoice_due_days" smallint NULL CHECK ("invoice_due_days" >= 0), "invoice_payment_terms" varchar(255) NOT NULL, "invoice_terms" text NOT NULL, "bank_name" varchar(120) NOT NULL, "bank_account_name" varchar(150) NOT NULL, "bank_account_number" varchar(30) NOT NULL, "bank_ifsc" varchar(11) NOT NULL, "upi_id" varchar(80) NOT NULL, "authorised_signatory" varchar(120) NOT NULL, "default_supplier_credit_days" smallint NULL CHECK ("default_supplier_credit_days" >= 0), "updated_at" timestamp with time zone NOT NULL);
CREATE TABLE "token_blacklist_blacklistedtoken" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "blacklisted_at" timestamp with time zone NOT NULL);
CREATE TABLE "token_blacklist_outstandingtoken" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "jti" uuid NOT NULL UNIQUE, "token" text NOT NULL, "created_at" timestamp with time zone NOT NULL, "expires_at" timestamp with time zone NOT NULL, "user_id" bigint NOT NULL);
ALTER TABLE "token_blacklist_blacklistedtoken" ADD COLUMN "token_id" integer NOT NULL UNIQUE CONSTRAINT "token_blacklist_blac_token_id_3cc7fe56_fk_token_bla" REFERENCES "token_blacklist_outstandingtoken"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "token_blacklist_blac_token_id_3cc7fe56_fk_token_bla" IMMEDIATE;
ALTER TABLE "token_blacklist_outstandingtoken" ADD CONSTRAINT "token_blacklist_outs_user_id_83bc629a_fk_accounts_" FOREIGN KEY ("user_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "token_blacklist_outstandingtoken_user_id_83bc629a" ON "token_blacklist_outstandingtoken" ("user_id");
ALTER TABLE "token_blacklist_outstandingtoken" ADD COLUMN "jti_hex" varchar(255) NULL;
ALTER TABLE "token_blacklist_outstandingtoken" ALTER COLUMN "jti_hex" SET NOT NULL;
ALTER TABLE "token_blacklist_outstandingtoken" ADD CONSTRAINT "token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq" UNIQUE ("jti_hex");
CREATE INDEX "token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like" ON "token_blacklist_outstandingtoken" ("jti_hex" varchar_pattern_ops);
ALTER TABLE "token_blacklist_outstandingtoken" DROP COLUMN "jti";
ALTER TABLE "token_blacklist_outstandingtoken" RENAME COLUMN "jti_hex" TO "jti";
ALTER TABLE "token_blacklist_outstandingtoken" ALTER COLUMN "created_at" DROP NOT NULL;
ALTER TABLE "token_blacklist_outstandingtoken" ALTER COLUMN "user_id" DROP NOT NULL;
ALTER TABLE "token_blacklist_outstandingtoken" ADD CONSTRAINT "token_blacklist_outs_user_id_83bc629a_fk_accounts_" FOREIGN KEY ("user_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "token_blacklist_blacklistedtoken" ALTER COLUMN "id" TYPE bigint USING "id"::bigint;
ALTER SEQUENCE IF EXISTS "token_blacklist_blacklistedtoken_id_seq" AS bigint;
ALTER TABLE "token_blacklist_outstandingtoken" ALTER COLUMN "id" TYPE bigint USING "id"::bigint;
ALTER SEQUENCE IF EXISTS "token_blacklist_outstandingtoken_id_seq" AS bigint;
ALTER TABLE "token_blacklist_blacklistedtoken" ALTER COLUMN "token_id" TYPE bigint USING "token_id"::bigint;
ALTER TABLE "token_blacklist_blacklistedtoken" ADD CONSTRAINT "token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk" FOREIGN KEY ("token_id") REFERENCES "token_blacklist_outstandingtoken" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public."django_content_type" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."auth_permission" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."auth_group" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."auth_group_permissions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."accounts_user" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."accounts_user_groups" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."accounts_user_user_permissions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."accounts_loginactivity" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."django_admin_log" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."ai_assistant_analyticsrun" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."ai_assistant_insight" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."ai_assistant_conversation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."ai_assistant_message" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."customers_customer" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."customers_customeroffer" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."finance_budget" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."finance_transaction" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."inventory_stockmovement" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."inventory_product" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."marketing_contentitem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."marketing_audiencesegment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."marketing_campaign" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."marketing_marketingmetric" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."marketing_scheduledpost" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."quality_certification" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."quality_qualityaudit" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."quality_qualitytest" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."quality_qualitystandard" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."purchase_supplier" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."purchase_rawmaterial" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."purchase_purchase" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."purchase_purchasereturn" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."purchase_supplierpayment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."purchase_goodsreceipt" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."purchase_materialmovement" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."reports_report" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."sales_salesorder" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."sales_salesorderitem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."sales_salesquotation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."sales_salesinvoice" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."sales_quotationstatuschange" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."sales_salesquotationitem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."sales_salesreturn" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."sales_salesinvoiceitem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."sales_salespayment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."django_session" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."system_backupsettings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."supply_chain_shipment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."system_companysettings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."system_notificationpreference" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."system_auditlog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."system_backuprun" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."system_notification" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."system_billingsettings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."token_blacklist_outstandingtoken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."token_blacklist_blacklistedtoken" ENABLE ROW LEVEL SECURITY;

-- Record the migrations as applied, so `manage.py migrate` skips them.
CREATE TABLE IF NOT EXISTS "django_migrations" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" timestamp with time zone NOT NULL);
INSERT INTO "django_migrations" ("app", "name", "applied") VALUES
    ('contenttypes', '0001_initial', now()),
    ('contenttypes', '0002_remove_content_type_name', now()),
    ('auth', '0001_initial', now()),
    ('auth', '0002_alter_permission_name_max_length', now()),
    ('auth', '0003_alter_user_email_max_length', now()),
    ('auth', '0004_alter_user_username_opts', now()),
    ('auth', '0005_alter_user_last_login_null', now()),
    ('auth', '0006_require_contenttypes_0002', now()),
    ('auth', '0007_alter_validators_add_error_messages', now()),
    ('auth', '0008_alter_user_username_max_length', now()),
    ('auth', '0009_alter_user_last_name_max_length', now()),
    ('auth', '0010_alter_group_name_max_length', now()),
    ('auth', '0011_update_proxy_permissions', now()),
    ('auth', '0012_alter_user_first_name_max_length', now()),
    ('accounts', '0001_initial', now()),
    ('accounts', '0002_alter_user_role', now()),
    ('admin', '0001_initial', now()),
    ('admin', '0002_logentry_remove_auto_add', now()),
    ('admin', '0003_logentry_add_action_flag_choices', now()),
    ('ai_assistant', '0001_initial', now()),
    ('ai_assistant', '0002_alter_insight_kind', now()),
    ('customers', '0001_initial', now()),
    ('customers', '0002_customer_gstin_customer_shipping_address_and_more', now()),
    ('finance', '0001_initial', now()),
    ('inventory', '0001_initial', now()),
    ('inventory', '0002_alter_stockmovement_source', now()),
    ('inventory', '0003_alter_stockmovement_source', now()),
    ('marketing', '0001_initial', now()),
    ('production', '0001_initial', now()),
    ('quality', '0001_initial', now()),
    ('purchase', '0001_initial', now()),
    ('quality', '0002_remove_qualitytest_batch_qualitytest_batch_number_and_more', now()),
    ('production', '0002_remove_productionbatch_batch_due_after_start_and_more', now()),
    ('production', '0003_delete_productionbatch', now()),
    ('reports', '0001_initial', now()),
    ('reports', '0002_alter_report_type', now()),
    ('reports', '0003_alter_report_type', now()),
    ('sales', '0001_initial', now()),
    ('sales', '0002_alter_salesorderitem_options_and_more', now()),
    ('sessions', '0001_initial', now()),
    ('supply_chain', '0001_initial', now()),
    ('supply_chain', '0002_move_to_purchase', now()),
    ('system', '0001_initial', now()),
    ('system', '0002_billingsettings', now()),
    ('token_blacklist', '0001_initial', now()),
    ('token_blacklist', '0002_outstandingtoken_jti_hex', now()),
    ('token_blacklist', '0003_auto_20171017_2007', now()),
    ('token_blacklist', '0004_auto_20171017_2013', now()),
    ('token_blacklist', '0005_remove_outstandingtoken_jti', now()),
    ('token_blacklist', '0006_auto_20171017_2113', now()),
    ('token_blacklist', '0007_auto_20171017_2214', now()),
    ('token_blacklist', '0008_migrate_to_bigautofield', now()),
    ('token_blacklist', '0010_fix_migrate_to_bigautofield', now()),
    ('token_blacklist', '0011_linearizes_history', now()),
    ('token_blacklist', '0012_alter_outstandingtoken_user', now()),
    ('token_blacklist', '0013_alter_blacklistedtoken_options_and_more', now());
ALTER TABLE "django_migrations" ENABLE ROW LEVEL SECURITY;

COMMIT;
