# Generated by Django 6.1.1 on 2026-10-01 10:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_gstin_customer_shipping_address_and_more'),
        ('inventory', '0003_alter_stockmovement_source'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesorderitem',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='salesorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='discount_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='gst_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14),
        ),
        migrations.CreateModel(
            name='SalesQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('customer_name', models.CharField(max_length=150)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('billing_address', models.TextField(blank=True)),
                ('shipping_address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gstin', models.CharField(blank=True, max_length=15, verbose_name='GSTIN')),
                ('quotation_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('quotation_date', models.DateField(db_index=True)),
                ('valid_until', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('converted', 'Converted')], db_index=True, default='draft', max_length=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('payment_terms', models.CharField(blank=True, max_length=255)),
                ('delivery_terms', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('terms_conditions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='customers.customer')),
            ],
            options={
                'ordering': ['-quotation_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('customer_name', models.CharField(max_length=150)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('billing_address', models.TextField(blank=True)),
                ('shipping_address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gstin', models.CharField(blank=True, max_length=15, verbose_name='GSTIN')),
                ('invoice_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('invoice_date', models.DateField(db_index=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('cancelled', 'Cancelled')], db_index=True, default='issued', max_length=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('credited_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('stock_moved', models.BooleanField(default=False, editable=False)),
                ('payment_terms', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('terms_conditions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customers.customer')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='sales.salesorder')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='sales.salesquotation')),
            ],
            options={
                'ordering': ['-invoice_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QuotationStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=10)),
                ('to_status', models.CharField(max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='sales.salesquotation')),
            ],
            options={
                'ordering': ['changed_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='salesorder',
            name='quotation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_order', to='sales.salesquotation'),
        ),
        migrations.CreateModel(
            name='SalesQuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('discount_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('gst_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_items', to='inventory.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesquotation')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('quantity_kg', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('return_date', models.DateField(db_index=True)),
                ('reason', models.CharField(choices=[('damaged', 'Damaged'), ('quality', 'Quality issue'), ('wrong_item', 'Wrong item'), ('excess', 'Excess quantity'), ('expired', 'Expired'), ('other', 'Other')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='credit amount')),
                ('restock', models.BooleanField(default=True, help_text='Put the returned goods back into sellable stock')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=10)),
                ('remarks', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='customers.customer')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.salesinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_returns', to='inventory.product')),
            ],
            options={
                'ordering': ['-return_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('discount_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('gst_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='inventory.product')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('invoice', 'product'), name='unique_product_per_invoice')],
            },
        ),
        migrations.CreateModel(
            name='SalesPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_date', models.DateField(db_index=True)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('cash', 'Cash'), ('card', 'Card'), ('other', 'Other')], max_length=13)),
                ('reference', models.CharField(blank=True, max_length=80, verbose_name='transaction reference')),
                ('status', models.CharField(choices=[('received', 'Received'), ('cancelled', 'Cancelled')], db_index=True, default='received', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='customers.customer')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.salesinvoice')),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='sales_payment_positive')],
            },
        ),
        migrations.AddConstraint(
            model_name='salesquotation',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__gte', models.F('quotation_date'))), name='quotation_valid_after_date'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__isnull', True), ('due_date__gte', models.F('invoice_date')), _connector='OR'), name='invoice_due_after_date'),
        ),
        migrations.AddConstraint(
            model_name='salesquotationitem',
            constraint=models.UniqueConstraint(fields=('quotation', 'product'), name='unique_product_per_quotation'),
        ),
        migrations.AddConstraint(
            model_name='salesreturn',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_kg__gt', 0)), name='sales_return_quantity_positive'),
        ),
    ]
